// This file is automatically generated - don't edit it. 
// Search Types for record CMS Content (cmscontent)

// Search Columns

/** CMS Content (cmscontent) Search Columns definition */
export interface cmscontentSearchColumn {
}


// Search Filters

/** CMS Content (cmscontent) Search Filters definition */
export interface cmscontentSearchFilter {
}


// Search Joins

/** CMS Content (cmscontent) Search Joins definitions. */
export interface cmscontentSearchJoin {
}


// Search Filter Types

/** CMS Content (cmscontent) Search Filter Type definitions. */
export interface cmscontentSearchFilterTypes {
}


// Search Column Types

/** CMS Content (cmscontent) Search Column Type definitions. */
export interface cmscontentSearchColumnTypes {
}