// This file is automatically generated - don't edit it. 
// Search Types for record Customer (customer)

// Search Columns

/** Customer (customer) Search Columns definition */
export interface customerSearchColumn {/** Account (accountnumber: text) */
  accountnumber?: string;
  /** Address (address: text) */
  address?: string;
  /** Addressee (addressee: text) */
  addressee?: string;
  /** Address Internal ID (addressinternalid: text) */
  addressinternalid?: string;
  /** Address Label (addresslabel: text) */
  addresslabel?: string;
  /** Address Phone (addressphone: text) */
  addressphone?: string;
  /** Alt. Contact (altcontact: text) */
  altcontact?: string;
  /** Alt. Email (altemail: email) */
  altemail?: string;
  /** Name (altname: text) */
  altname?: string;
  /** Office Phone (altphone: phone) */
  altphone?: string;
  /** Assigned Web Site (assignedsite: select) */
  assignedsite?: string;
  /** Attention (attention: text) */
  attention?: string;
  /** Always Available Offline (availableoffline: checkbox) */
  availableoffline?: boolean;
  /** Balance (balance: currency) */
  balance?: string;
  /** Billing Country Code (billcountrycode: text) */
  billcountrycode?: string;
  /** Billing Zip (billzipcode: text) */
  billzipcode?: string;
  /** Buying Reason (buyingreason: text) */
  buyingreason?: string;
  /** Buying Time Frame (buyingtimeframe: text) */
  buyingtimeframe?: string;
  /** Category (category: select) */
  category?: string;
  /** CC Customer Code (cccustomercode: text) */
  cccustomercode?: string;
  /** Default Credit Card (ccdefault: checkbox) */
  ccdefault?: boolean;
  /** CC Expire Date (ccexpdate: mmyydate) */
  ccexpdate?: string;
  /** Credit Cardholder Name (ccholdername: text) */
  ccholdername?: string;
  /** Credit Card Internal ID (ccinternalid: text) */
  ccinternalid?: string;
  /** Credit Card Number (ccnumber: ccnumber) */
  ccnumber?: string;
  /** Credit Card Type (cctype: select) */
  cctype?: string;
  /** City (city: text) */
  city?: string;
  /** Comments (comments: text) */
  comments?: string;
  /** Company Name (companyname: text) */
  companyname?: string;
  /** Consolidated Balance (consolbalance: currency) */
  consolbalance?: string;
  /** Consolidated Days Overdue (consoldaysoverdue: integer) */
  consoldaysoverdue?: number;
  /** Consolidated Deposit Balance (consoldepositbalance: currency) */
  consoldepositbalance?: string;
  /** Consolidated Overdue Balance (consoloverduebalance: currency) */
  consoloverduebalance?: string;
  /** Consolidated Unbilled Orders (consolunbilledorders: currency) */
  consolunbilledorders?: string;
  /** Primary Contact (contact: select) */
  contact?: string;
  /** Contribution % (contribution: percent) */
  contribution?: string;
  /** Primary Sales Rep Contribution % (contributionprimary: percent) */
  contributionprimary?: string;
  /** Conversion Date (conversiondate: date) */
  conversiondate?: Date;
  /** Country (country: select) */
  country?: string;
  /** Country Code (countrycode: text) */
  countrycode?: string;
  /** Credit Hold (credithold: select) */
  credithold?: string;
  /** Override Credit Hold Off (creditholdoverride: checkbox) */
  creditholdoverride?: boolean;
  /** Credit Limit (creditlimit: currency) */
  creditlimit?: string;
  /** Currency (currency: select) */
  currency?: string;
  /** Date Closed (dateclosed: datetime) */
  dateclosed?: string;
  /** Date Created (datecreated: datetime) */
  datecreated?: string;
  /** Days Overdue (daysoverdue: integer) */
  daysoverdue?: number;
  /** Default Order Priority (defaultorderpriority: text) */
  defaultorderpriority?: string;
  /** Deposit Balance (depositbalance: currency) */
  depositbalance?: string;
  /** Deferred Revenue Reclassification Account (draccount: text) */
  draccount?: string;
  /** Email (email: email) */
  email?: string;
  /** Email Preference (emailpreference: select) */
  emailpreference?: string;
  /** Email Transactions (emailtransactions: checkbox) */
  emailtransactions?: boolean;
  /** End Date (enddate: date) */
  enddate?: Date;
  /** Name (entityid: text) */
  entityid?: string;
  /** Number (entitynumber: integer) */
  entitynumber?: number;
  /** Status (entitystatus: select) */
  entitystatus?: string;
  /** Estimated Budget (estimatedbudget: currency) */
  estimatedbudget?: string;
  /** Explicit Conversion (explicitconversion: checkbox) */
  explicitconversion?: boolean;
  /** External ID (externalid: select) */
  externalid?: string;
  /** Fax (fax: text) */
  fax?: string;
  /** Fax Transactions (faxtransactions: checkbox) */
  faxtransactions?: boolean;
  /** First Name (firstname: text) */
  firstname?: string;
  /** Date of First Order (firstorderdate: date) */
  firstorderdate?: Date;
  /** Date of First Sale (firstsaledate: date) */
  firstsaledate?: Date;
  /** Formula (Currency) (formulacurrency: currency) */
  formulacurrency?: string;
  /** Formula (Date) (formuladate: date) */
  formuladate?: Date;
  /** Formula (Date/Time) (formuladatetime: datetime) */
  formuladatetime?: string;
  /** Formula (Numeric) (formulanumeric: float) */
  formulanumeric?: number;
  /** Formula (Percent) (formulapercent: percent) */
  formulapercent?: string;
  /** Formula (Text) (formulatext: text) */
  formulatext?: string;
  /** Foreign Currency Adjustment Revenue Account (fxaccount: text) */
  fxaccount?: string;
  /** Balance (Foreign Currency) (fxbalance: currency) */
  fxbalance?: string;
  /** Consolidated Balance (Foreign Currency) (fxconsolbalance: currency) */
  fxconsolbalance?: string;
  /** Consolidated Unbilled Orders (Foreign Currency) (fxconsolunbilledorders: currency) */
  fxconsolunbilledorders?: string;
  /** Unbilled Orders (Foreign Currency) (fxunbilledorders: currency) */
  fxunbilledorders?: string;
  /** Login Access (giveaccess: checkbox) */
  giveaccess?: boolean;
  /** Global Subscription Status (globalsubscriptionstatus: select) */
  globalsubscriptionstatus?: string;
  /** Group Pricing Level (grouppricinglevel: text) */
  grouppricinglevel?: string;
  /** Duplicate (hasduplicates: checkbox) */
  hasduplicates?: boolean;
  /** Home Phone (homephone: phone) */
  homephone?: string;
  /** Image (image: select) */
  image?: string;
  /** Internal ID (internalid: select) */
  internalid?: string;
  /** Budget Approved (isbudgetapproved: checkbox) */
  isbudgetapproved?: boolean;
  /** Default Billing Address (isdefaultbilling: checkbox) */
  isdefaultbilling?: boolean;
  /** Default Shipping Address (isdefaultshipping: checkbox) */
  isdefaultshipping?: boolean;
  /** Inactive (isinactive: checkbox) */
  isinactive?: boolean;
  /** Is Individual (isperson: checkbox) */
  isperson?: boolean;
  /** Residential Address (isshipaddress: checkbox) */
  isshipaddress?: boolean;
  /** Item Pricing Level (itempricinglevel: text) */
  itempricinglevel?: string;
  /** Item Pricing Unit Price (itempricingunitprice: currency) */
  itempricingunitprice?: string;
  /** Job Actual End (jobenddate: date) */
  jobenddate?: Date;
  /** Job Projected End (jobprojectedend: date) */
  jobprojectedend?: Date;
  /** Job Start (jobstartdate: date) */
  jobstartdate?: Date;
  /** Job Type (jobtype: select) */
  jobtype?: string;
  /** Language (language: select) */
  language?: string;
  /** Last Modified (lastmodifieddate: datetime) */
  lastmodifieddate?: string;
  /** Last Name (lastname: text) */
  lastname?: string;
  /** Date of Last Order (lastorderdate: date) */
  lastorderdate?: Date;
  /** Date of Last Sale (lastsaledate: date) */
  lastsaledate?: Date;
  /** Last Viewed (lastviewed: datetime) */
  lastviewed?: string;
  /** Lead Date (leaddate: datetime) */
  leaddate?: string;
  /** Lead Source (leadsource: select) */
  leadsource?: string;
  /** Level (level: select) */
  level?: string;
  /** Override Credit Hold On (manualcredithold: checkbox) */
  manualcredithold?: boolean;
  /** Middle Name (middlename: text) */
  middlename?: string;
  /** Mobile Phone (mobilephone: phone) */
  mobilephone?: string;
  /** Monthly Closing Date (monthlyclosing: select) */
  monthlyclosing?: string;
  /** On Credit Hold (oncredithold: checkbox) */
  oncredithold?: boolean;
  /** Online Form History - Date (onlineformdate: text) */
  onlineformdate?: string;
  /** Online Form History - Lead Source (onlineformleadsource: text) */
  onlineformleadsource?: string;
  /** Online Form History - Form Name (onlineformname: text) */
  onlineformname?: string;
  /** Overdue Balance (overduebalance: currency) */
  overduebalance?: string;
  /** Top Level Parent (parent: select) */
  parent?: string;
  /** Partner (partner: select) */
  partner?: string;
  /** Partner Contribution % (partnercontribution: percent) */
  partnercontribution?: string;
  /** Partner Role (partnerrole: text) */
  partnerrole?: string;
  /** Partner Team Member (partnerteammember: select) */
  partnerteammember?: string;
  /** PEC (pec: text) */
  pec?: string;
  /** Permission (permission: select) */
  permission?: string;
  /** Phone (phone: phone) */
  phone?: string;
  /** Phonetic Name (phoneticname: text) */
  phoneticname?: string;
  /** Credit Card Processor (prefccprocessor: select) */
  prefccprocessor?: string;
  /** Price Level (pricelevel: select) */
  pricelevel?: string;
  /** Pricing Group (pricinggroup: text) */
  pricinggroup?: string;
  /** Pricing Item (pricingitem: text) */
  pricingitem?: string;
  /** Print Transactions (printtransactions: checkbox) */
  printtransactions?: boolean;
  /** Prospect Date (prospectdate: datetime) */
  prospectdate?: string;
  /** Default Receivables Account (receivablesaccount: text) */
  receivablesaccount?: string;
  /** Reminder Days (reminderdays: integer) */
  reminderdays?: number;
  /** Represents Subsidiary (representingsubsidiary: select) */
  representingsubsidiary?: string;
  /** Resale Number (resalenumber: text) */
  resalenumber?: string;
  /** Role (role: text) */
  role?: string;
  /** Sales Readiness (salesreadiness: text) */
  salesreadiness?: string;
  /** Sales Rep (salesrep: select) */
  salesrep?: string;
  /** Sales Team Member (salesteammember: select) */
  salesteammember?: string;
  /** Sales Team Role (salesteamrole: select) */
  salesteamrole?: string;
  /** Mr./Mrs... (salutation: text) */
  salutation?: string;
  /** Ship Complete (shipcomplete: checkbox) */
  shipcomplete?: boolean;
  /** Shipping Country Code (shipcountrycode: text) */
  shipcountrycode?: string;
  /** Shipping Carrier (shippingcarrier: select) */
  shippingcarrier?: string;
  /** Shipping Item (shippingitem: select) */
  shippingitem?: string;
  /** Source Website (sourcesite: select) */
  sourcesite?: string;
  /** Stage (stage: select) */
  stage?: string;
  /** Start Date (startdate: date) */
  startdate?: Date;
  /** State/Province (state: select) */
  state?: string;
  /** State/Province Display Name (statedisplayname: select) */
  statedisplayname?: string;
  /** Subscription (subscription: select) */
  subscription?: string;
  /** Subscription Date (subscriptiondate: datetime) */
  subscriptiondate?: string;
  /** Subscription Status (subscriptionstatus: checkbox) */
  subscriptionstatus?: boolean;
  /** Subsidiary (subsidiary: select) */
  subsidiary?: string;
  /** Subsidiary (no hierarchy) (subsidiarynohierarchy: select) */
  subsidiarynohierarchy?: string;
  /** Taxable (taxable: checkbox) */
  taxable?: boolean;
  /** Tax Item (taxitem: select) */
  taxitem?: string;
  /** Terms (terms: select) */
  terms?: string;
  /** Territory (territory: select) */
  territory?: string;
  /** Job Title (title: text) */
  title?: string;
  /** Type (type: select) */
  type?: string;
  /** Unbilled Orders (unbilledorders: currency) */
  unbilledorders?: string;
  /** Web Address (url: text) */
  url?: string;
  /** Tax Number (vatregnumber: text) */
  vatregnumber?: string;
  /** Web Lead (weblead: checkbox) */
  weblead?: boolean;
  /** Zip Code (zipcode: text) */
  zipcode?: string;
}


// Search Filters

/** Customer (customer) Search Filters definition */
export interface customerSearchFilter {/** Account (accountnumber: text) */
  accountnumber?: string;
  /** Address (address: textarea) */
  address?: string;
  /** Addressee (addressee: text) */
  addressee?: string;
  /** Address Label (addresslabel: text) */
  addresslabel?: string;
  /** Address Phone (addressphone: phone) */
  addressphone?: string;
  /** Assigned Web Site (assignedsite: select) */
  assignedsite?: string;
  /** Attention (attention: text) */
  attention?: string;
  /** Always Available Offline (availableoffline: checkbox) */
  availableoffline?: boolean;
  /** Balance (balance: currency) */
  balance?: string;
  /** Total Amount Purchased (boughtamount: currency) */
  boughtamount?: string;
  /** Purchase Dates (boughtdate: date) */
  boughtdate?: Date;
  /** Buying Reason (buyingreason: select) */
  buyingreason?: string;
  /** Buying Time Frame (buyingtimeframe: select) */
  buyingtimeframe?: string;
  /** Category (category: select) */
  category?: string;
  /** CC Customer Code (cccustomercode: text) */
  cccustomercode?: string;
  /** Default Credit Card (ccdefault: checkbox) */
  ccdefault?: boolean;
  /** CC Expire Date (ccexpdate: date) */
  ccexpdate?: Date;
  /** Credit Cardholder Name (ccholdername: text) */
  ccholdername?: string;
  /** Credit Card Number (ccnumber: ccnumber) */
  ccnumber?: string;
  /** Credit Card Type (cctype: select) */
  cctype?: string;
  /** City (city: text) */
  city?: string;
  /** Class (classbought: multiselect) */
  classbought?: string;
  /** Comments (comments: textarea) */
  comments?: string;
  /** Company Name (companyname: text) */
  companyname?: string;
  /** Consolidated Balance (consolbalance: currency) */
  consolbalance?: string;
  /** Consolidated Days Overdue (consoldaysoverdue: integer) */
  consoldaysoverdue?: number;
  /** Consolidated Deposit Balance (consoldepositbalance: currency) */
  consoldepositbalance?: string;
  /** Consolidated Overdue Balance (consoloverduebalance: currency) */
  consoloverduebalance?: string;
  /** Consolidated Unbilled Orders (consolunbilledorders: currency) */
  consolunbilledorders?: string;
  /** Contact (contact: text) */
  contact?: string;
  /** Contribution % (contribution: integer) */
  contribution?: number;
  /** Conversion Date (conversiondate: date) */
  conversiondate?: Date;
  /** Country (country: select) */
  country?: string;
  /** County/State (county: text) */
  county?: string;
  /** Credit Hold (credithold: select) */
  credithold?: string;
  /** Override Credit Hold Off (creditholdoverride: checkbox) */
  creditholdoverride?: boolean;
  /** Credit Limit (creditlimit: currency) */
  creditlimit?: string;
  /** Currency (currency: select) */
  currency?: string;
  /** Parent Stage (custstage: select) */
  custstage?: string;
  /** Parent Status (custstatus: select) */
  custstatus?: string;
  /** Date Closed (dateclosed: datetime) */
  dateclosed?: string;
  /** Date Created (datecreated: datetime) */
  datecreated?: string;
  /** Days Overdue (daysoverdue: integer) */
  daysoverdue?: number;
  /** Default Order Priority (defaultorderpriority: text) */
  defaultorderpriority?: string;
  /** Deposit Balance (depositbalance: currency) */
  depositbalance?: string;
  /** Department (deptbought: multiselect) */
  deptbought?: string;
  /** Deferred Revenue Reclassification Account (draccount: select) */
  draccount?: string;
  /** Email (email: text) */
  email?: string;
  /** Email Preference (emailpreference: select) */
  emailpreference?: string;
  /** Email Transactions (emailtransactions: checkbox) */
  emailtransactions?: boolean;
  /** End Date (enddate: date) */
  enddate?: Date;
  /** Name/ID (entityid: text) */
  entityid?: string;
  /** Status (entitystatus: select) */
  entitystatus?: string;
  /** Estimated Budget (estimatedbudget: currency) */
  estimatedbudget?: string;
  /** Explicit Conversion (explicitconversion: checkbox) */
  explicitconversion?: boolean;
  /** External ID (externalid: select) */
  externalid?: string;
  /** External ID (Text) (externalidstring: text) */
  externalidstring?: string;
  /** Fax (fax: phone) */
  fax?: string;
  /** Fax Transactions (faxtransactions: checkbox) */
  faxtransactions?: boolean;
  /** First Name (firstname: text) */
  firstname?: string;
  /** Date of First Order (firstorderdate: date) */
  firstorderdate?: Date;
  /** Date of First Sale (firstsaledate: date) */
  firstsaledate?: Date;
  /** Formula (Date) (formuladate: date) */
  formuladate?: Date;
  /** Formula (Numeric) (formulanumeric: float) */
  formulanumeric?: number;
  /** Formula (Text) (formulatext: text) */
  formulatext?: string;
  /** Foreign Currency Adjustment Revenue Account (fxaccount: select) */
  fxaccount?: string;
  /** Balance (Foreign Currency) (fxbalance: currency) */
  fxbalance?: string;
  /** Consolidated Balance (Foreign Currency) (fxconsolbalance: currency) */
  fxconsolbalance?: string;
  /** Consolidated Unbilled Orders (Foreign Currency) (fxconsolunbilledorders: currency) */
  fxconsolunbilledorders?: string;
  /** Unbilled Orders (Foreign Currency) (fxunbilledorders: currency) */
  fxunbilledorders?: string;
  /** Login Access (giveaccess: checkbox) */
  giveaccess?: boolean;
  /** Global Subscription Status (globalsubscriptionstatus: select) */
  globalsubscriptionstatus?: string;
  /** Group (group: multiselect) */
  group?: string;
  /** Group Pricing Level (grouppricinglevel: select) */
  grouppricinglevel?: string;
  /** Duplicate (hasduplicates: checkbox) */
  hasduplicates?: boolean;
  /** Image (image: image) */
  image?: string;
  /** Internal ID (internalid: select) */
  internalid?: string;
  /** Internal ID (Number) (internalidnumber: integer) */
  internalidnumber?: number;
  /** Budget Approved (isbudgetapproved: checkbox) */
  isbudgetapproved?: boolean;
  /** Default Billing Address (isdefaultbilling: checkbox) */
  isdefaultbilling?: boolean;
  /** Default Shipping Address (isdefaultshipping: checkbox) */
  isdefaultshipping?: boolean;
  /** Inactive (isinactive: checkbox) */
  isinactive?: boolean;
  /** Is Job (isjob: checkbox) */
  isjob?: boolean;
  /** Is Individual (isperson: checkbox) */
  isperson?: boolean;
  /** Included in Lead Reports (isreportedlead: checkbox) */
  isreportedlead?: boolean;
  /** Residential Address (isshipaddress: checkbox) */
  isshipaddress?: boolean;
  /** Item Pricing Level (itempricinglevel: select) */
  itempricinglevel?: string;
  /** Item Pricing Unit Price (itempricingunitprice: currency) */
  itempricingunitprice?: string;
  /** Items Purchased (itemsbought: multiselect) */
  itemsbought?: string;
  /** Items Ordered (itemsordered: multiselect) */
  itemsordered?: string;
  /** Actual End Date (jobenddate: date) */
  jobenddate?: Date;
  /** Estimated Cost (jobestcost: currency) */
  jobestcost?: string;
  /** Projected End Date (jobestenddate: date) */
  jobestenddate?: Date;
  /** Estimated Revenue (jobestrevenue: currency) */
  jobestrevenue?: string;
  /** Percent Complete (jobpctcomplete: integer) */
  jobpctcomplete?: number;
  /** Start Date (jobstartdate: date) */
  jobstartdate?: Date;
  /** Job Status (jobstatus: select) */
  jobstatus?: string;
  /** Job Type (jobtype: select) */
  jobtype?: string;
  /** Language (language: select) */
  language?: string;
  /** Last Modified (lastmodifieddate: datetime) */
  lastmodifieddate?: string;
  /** Last Name (lastname: text) */
  lastname?: string;
  /** Date of Last Order (lastorderdate: date) */
  lastorderdate?: Date;
  /** Date of Last Sale (lastsaledate: date) */
  lastsaledate?: Date;
  /** Lead Date (leaddate: datetime) */
  leaddate?: string;
  /** Lead Source (leadsource: select) */
  leadsource?: string;
  /** Level (level: select) */
  level?: string;
  /** Location (locationbought: multiselect) */
  locationbought?: string;
  /** Override Credit Hold On (manualcredithold: checkbox) */
  manualcredithold?: boolean;
  /** Credit Card Processor (merchantaccount: select) */
  merchantaccount?: string;
  /** Middle Name (middlename: text) */
  middlename?: string;
  /** Monthly Closing Date (monthlyclosing: select) */
  monthlyclosing?: string;
  /** On Credit Hold (oncredithold: checkbox) */
  oncredithold?: boolean;
  /** Online Form History - Form Date (onlineformdate: date) */
  onlineformdate?: Date;
  /** Online Form History - Lead Source (onlineformleadsource: select) */
  onlineformleadsource?: string;
  /** Online Form History - Form Name (onlineformname: select) */
  onlineformname?: string;
  /** Total Amount Ordered (orderedamount: currency) */
  orderedamount?: string;
  /** Order Dates (ordereddate: date) */
  ordereddate?: Date;
  /** Other Relationships (otherrelationships: multiselect) */
  otherrelationships?: string;
  /** Overdue Balance (overduebalance: currency) */
  overduebalance?: string;
  /** Sub of (parent: select) */
  parent?: string;
  /** Items or Sub-Items Purchased (parentitemsbought: multiselect) */
  parentitemsbought?: string;
  /** Items or Sub-Items Ordered (parentitemsordered: multiselect) */
  parentitemsordered?: string;
  /** Partner (partner: select) */
  partner?: string;
  /** Partner Contribution % (partnercontribution: integer) */
  partnercontribution?: number;
  /** Partner Role (partnerrole: select) */
  partnerrole?: string;
  /** Partner Team Member (partnerteammember: select) */
  partnerteammember?: string;
  /** PEC (pec: text) */
  pec?: string;
  /** Permission (permission: select) */
  permission?: string;
  /** Phone (phone: phone) */
  phone?: string;
  /** Phonetic Name (phoneticname: text) */
  phoneticname?: string;
  /** Price Level (pricelevel: select) */
  pricelevel?: string;
  /** Pricing Group (pricinggroup: select) */
  pricinggroup?: string;
  /** Pricing Item (pricingitem: select) */
  pricingitem?: string;
  /** Print Transactions (printtransactions: checkbox) */
  printtransactions?: boolean;
  /** Prospect Date (prospectdate: datetime) */
  prospectdate?: string;
  /** PST Exempt (pstexempt: checkbox) */
  pstexempt?: boolean;
  /** Default Receivables Account (receivablesaccount: select) */
  receivablesaccount?: string;
  /** Renewal Reminder Date (reminderdate: date) */
  reminderdate?: Date;
  /** Represents Subsidiary (representingsubsidiary: select) */
  representingsubsidiary?: string;
  /** Resale Number (resalenumber: text) */
  resalenumber?: string;
  /** Role (role: select) */
  role?: string;
  /** Sales Readiness (salesreadiness: select) */
  salesreadiness?: string;
  /** Sales Rep (salesrep: select) */
  salesrep?: string;
  /** Sales Team Member (salesteammember: select) */
  salesteammember?: string;
  /** Sales Team Role (salesteamrole: select) */
  salesteamrole?: string;
  /** Mr./Mrs... (salutation: text) */
  salutation?: string;
  /** Ship Complete (shipcomplete: checkbox) */
  shipcomplete?: boolean;
  /** Shipping Carrier (shippingcarrier: select) */
  shippingcarrier?: string;
  /** Shipping Item (shippingitem: select) */
  shippingitem?: string;
  /** Source Website (sourcesite: select) */
  sourcesite?: string;
  /** Stage (stage: select) */
  stage?: string;
  /** Start Date (startdate: date) */
  startdate?: Date;
  /** State/Province (state: select) */
  state?: string;
  /** Subsidiaries Bought (subsidbought: multiselect) */
  subsidbought?: string;
  /** Subsidiary (subsidiary: select) */
  subsidiary?: string;
  /** Taxable (taxable: checkbox) */
  taxable?: boolean;
  /** Terms (terms: select) */
  terms?: string;
  /** Territory (territory: select) */
  territory?: string;
  /** Job Title (title: text) */
  title?: string;
  /** Entity Type (type: select) */
  type?: string;
  /** Unbilled Orders (unbilledorders: currency) */
  unbilledorders?: string;
  /** Web Address (url: url) */
  url?: string;
  /** Tax Number (vatregnumber: text) */
  vatregnumber?: string;
  /** Web Lead (weblead: checkbox) */
  weblead?: boolean;
  /** Zip (zipcode: text) */
  zipcode?: string;
}


// Search Joins
/** Customer (customer) Search Joins definition type. */
export interface customerSearchJoin {/** customer's billingschedule search filter. Billing Schedule. Actual name: Billing Schedule. */
  billingschedule: 'billingschedule';
  /** customer's campaignresponse search filter. Campaign Response. Actual name: Campaign. */
  campaignresponse: 'campaignresponse';
  /** customer's contact search filter. Contact. Actual name: Contact. */
  contact: 'contact';
  /** customer's contactprimary search filter. Contact (Primary). Actual name: Contact. */
  contactprimary: 'contactprimary';
  /** customer's job search filter. Job. Actual name: Job. */
  job: 'job';
  /** customer's leadsource search filter. Lead Source. Actual name: Campaign. */
  leadsource: 'leadsource';
  /** customer's messages search filter. Messages. Actual name: Message. */
  messages: 'messages';
  /** customer's messagesfrom search filter. Messages From. Actual name: Message. */
  messagesfrom: 'messagesfrom';
  /** customer's messagesto search filter. Messages To. Actual name: Message. */
  messagesto: 'messagesto';
  /** customer's msesubsidiary search filter. Subsidiary. Actual name: Subsidiary. */
  msesubsidiary: 'msesubsidiary';
  /** customer's originatinglead search filter. Originating Lead. Actual name: Lead. */
  originatinglead: 'originatinglead';
  /** customer's parentcustomer search filter. Parent Customer. Actual name: Customer. */
  parentcustomer: 'parentcustomer';
  /** customer's partner search filter. Partner. Actual name: Partner. */
  partner: 'partner';
  /** customer's pricing search filter. Pricing. Actual name: Pricing. */
  pricing: 'pricing';
  /** customer's salesrep search filter. Sales Rep. Actual name: Employee. */
  salesrep: 'salesrep';
  /** customer's subcustomer search filter. Sub Customer. Actual name: Customer. */
  subcustomer: 'subcustomer';
  /** customer's task search filter. Task. Actual name: Task. */
  task: 'task';
  /** customer's toplevelparent search filter. Top Level Parent. Actual name: Customer. */
  toplevelparent: 'toplevelparent';
  /** customer's websitecategory search filter. Web Site Category. Actual name: Presentation Category. */
  websitecategory: 'websitecategory';
}