// This file is automatically generated - don't edit it. 
// Search Types for record Inventory Part (inventoryitem)

// Search Columns

/** Inventory Part (inventoryitem) Search Columns definition */
export interface inventoryitemSearchColumn {
}


// Search Filters

/** Inventory Part (inventoryitem) Search Filters definition */
export interface inventoryitemSearchFilter {
}


// Search Joins
/** Inventory Part (inventoryitem) Search Joins definition type. */
export interface inventoryitemSearchJoin {
}