// This file is automatically generated - don't edit it. 
// Search Types for record Invoice (invoice)

// Search Columns

/** Invoice (invoice) Search Columns definition */
export interface invoiceSearchColumn {
}


// Search Filters

/** Invoice (invoice) Search Filters definition */
export interface invoiceSearchFilter {
}


// Search Joins

/** Invoice (invoice) Search Joins definitions. */
export interface invoiceSearchJoin {
}


// Search Filter Types

/** Invoice (invoice) Search Filter Type definitions. */
export interface invoiceSearchFilterTypes {
}


// Search Column Types

/** Invoice (invoice) Search Column Type definitions. */
export interface invoiceSearchColumnTypes {
}