// This file is automatically generated - don't edit it. 
// Search Types for record Invoice (invoice)

// Search Columns

/** Invoice (invoice) Search Columns definition */
export interface invoiceSearchColumn {
}


// Search Filters

/** Invoice (invoice) Search Filters definition */
export interface invoiceSearchFilter {
}


// Search Joins
/** Invoice (invoice) Search Joins definition type. */
export interface invoiceSearchJoin {
}