// This file is automatically generated - don't edit it. 
// Search Types for record Item (item)

// Search Columns

/** Item (item) Search Columns definition */
export interface itemSearchColumn {/** Accounting Book Rev Rec Forecast Rule (accbookrevrecforecastrule: select) */
  accbookrevrecforecastrule?: string;
  /** Accounting Book (accountingbook: select) */
  accountingbook?: string;
  /** Accounting Book Amortization Schedule (accountingbookamortization: select) */
  accountingbookamortization?: string;
  /** Accounting Book Create Revenue Plans On (accountingbookcreateplanson: select) */
  accountingbookcreateplanson?: string;
  /** Accounting Book Revenue Recognition Rule (accountingbookrevrecrule: select) */
  accountingbookrevrecrule?: string;
  /** Accounting Book Rev. Rec. Schedule (accountingbookrevrecschedule: select) */
  accountingbookrevrecschedule?: string;
  /** Alternate Source Item (alternatedemandsourceitem: text) */
  alternatedemandsourceitem?: string;
  /** Asset Account (assetaccount: select) */
  assetaccount?: string;
  /** ATP Lead Time (atpleadtime: float) */
  atpleadtime?: number;
  /** Default ATP Method (atpmethod: text) */
  atpmethod?: string;
  /** Auto Lead Time (autoleadtime: checkbox) */
  autoleadtime?: boolean;
  /** Auto Stock Level (autopreferredstocklevel: checkbox) */
  autopreferredstocklevel?: boolean;
  /** Auto Reorder Point (autoreorderpoint: checkbox) */
  autoreorderpoint?: boolean;
  /** Available to Partners (availabletopartners: checkbox) */
  availabletopartners?: boolean;
  /** Average Cost (averagecost: currency2) */
  averagecost?: number;
  /** Backward Consumption Days (backwardconsumptiondays: integer) */
  backwardconsumptiondays?: number;
  /** Base Price (baseprice: currency2) */
  baseprice?: number;
  /** Bill Exchange Rate Variance Account (billexchratevarianceacct: select) */
  billexchratevarianceacct?: string;
  /** Bill Price Variance Account (billpricevarianceacct: select) */
  billpricevarianceacct?: string;
  /** Bill Quantity Variance Account (billqtyvarianceacct: select) */
  billqtyvarianceacct?: string;
  /** Bin Number (binnumber: text) */
  binnumber?: string;
  /** Bin On Hand Available (binonhandavail: float) */
  binonhandavail?: number;
  /** Bin On Hand Count (binonhandcount: float) */
  binonhandcount?: number;
  /** BOM Quantity (bomquantity: float) */
  bomquantity?: number;
  /** Build Sub-Assemblies (buildentireassembly: checkbox) */
  buildentireassembly?: boolean;
  /** Work Order Lead Time (buildtime: float) */
  buildtime?: number;
  /** eBay Buy It Now Price (buyitnowprice: currency) */
  buyitnowprice?: number;
  /** Category (category: text) */
  category?: string;
  /** Category (no hierarchy) (categorynohierarchy: text) */
  categorynohierarchy?: string;
  /** Category (preferred) (categorypreferred: text) */
  categorypreferred?: string;
  /** Class (class: select) */
  class?: string;
  /** Class (no hierarchy) (classnohierarchy: select) */
  classnohierarchy?: string;
  /** Component Yield (componentyield: float) */
  componentyield?: number;
  /** Eligible for Contingent Revenue Handling (contingentrevenuehandling: checkbox) */
  contingentrevenuehandling?: boolean;
  /** Copy SO Descr. (copydescription: checkbox) */
  copydescription?: boolean;
  /** Correlated Item (correlateditem: select) */
  correlateditem?: string;
  /** Correlated Item Correlation (correlateditemcorrelation: float) */
  correlateditemcorrelation?: number;
  /** Correlated Item Count (correlateditemcount: integer) */
  correlateditemcount?: number;
  /** Correlated Item Lift (correlateditemlift: float) */
  correlateditemlift?: number;
  /** Correlated Item Purchase Rate (correlateditempurchaserate: float) */
  correlateditempurchaserate?: number;
  /** Purchase Price (cost: currency2) */
  cost?: number;
  /** Cost Accounting Status (costaccountingstatus: text) */
  costaccountingstatus?: string;
  /** Cost Category (costcategory: text) */
  costcategory?: string;
  /** Item Defined Cost (costestimate: currency2) */
  costestimate?: number;
  /** Cost Estimate Type (costestimatetype: text) */
  costestimatetype?: string;
  /** Costing Method (costingmethod: select) */
  costingmethod?: string;
  /** Manufacturer Country (countryofmanufacture: text) */
  countryofmanufacture?: string;
  /** Date Created (created: datetime) */
  created?: Date;
  /** Create Job (createjob: checkbox) */
  createjob?: boolean;
  /** Create Revenue Plans On (createrevenueplanson: select) */
  createrevenueplanson?: string;
  /** Current Standard Cost (currentstandardcost: currency2) */
  currentstandardcost?: number;
  /** Current Standard Cost Effective Date (currentstdcosteffectivedate: date) */
  currentstdcosteffectivedate?: Date;
  /** Customer Return Variance Account (custreturnvarianceaccount: select) */
  custreturnvarianceaccount?: string;
  /** Date Viewed (dateviewed: datetime) */
  dateviewed?: Date;
  /** Days Before Expiration (daysbeforeexpiration: text) */
  daysbeforeexpiration?: string;
  /** Default Return Cost (defaultreturncost: currency2) */
  defaultreturncost?: number;
  /** Deferred Expense Account (deferredexpenseaccount: select) */
  deferredexpenseaccount?: string;
  /** Deferred Revenue Account (deferredrevenueaccount: select) */
  deferredrevenueaccount?: string;
  /** Hold Revenue Recognition (deferrevrec: checkbox) */
  deferrevrec?: boolean;
  /** Expected Demand Change (demandmodifier: percent) */
  demandmodifier?: number;
  /** Demand Source (demandsource: text) */
  demandsource?: string;
  /** Department (department: select) */
  department?: string;
  /** Department (no hierarchy) (departmentnohierarchy: select) */
  departmentnohierarchy?: string;
  /** Direct Revenue Posting (directrevenueposting: checkbox) */
  directrevenueposting?: boolean;
  /** eBay Store (displayinebaystore: checkbox) */
  displayinebaystore?: boolean;
  /** Display Name (displayname: text) */
  displayname?: string;
  /** Distribution Category (distributioncategory: text) */
  distributioncategory?: string;
  /** Distribution Network (distributionnetwork: text) */
  distributionnetwork?: string;
  /** Don't Show Price (dontshowprice: checkbox) */
  dontshowprice?: boolean;
  /** eBay Description (ebayitemdescription: clobtext) */
  ebayitemdescription?: string;
  /** eBay Subtitle (ebayitemsubtitle: text) */
  ebayitemsubtitle?: string;
  /** eBay Title (ebayitemtitle: text) */
  ebayitemtitle?: string;
  /** eBay Relisting Option (ebayrelistingoption: text) */
  ebayrelistingoption?: string;
  /** Effective BOM Control (effectivebomcontrol: text) */
  effectivebomcontrol?: string;
  /** Effective Date (effectivedate: date) */
  effectivedate?: Date;
  /** Effective Revision (effectiverevision: select) */
  effectiverevision?: string;
  /** eBay End Auctions When Out of Stock (endauctionswhenoutofstock: checkbox) */
  endauctionswhenoutofstock?: boolean;
  /** Exclude from Sitemap (excludefromsitemap: checkbox) */
  excludefromsitemap?: boolean;
  /** Expense/COGS Account (expenseaccount: select) */
  expenseaccount?: string;
  /** External ID (externalid: select) */
  externalid?: string;
  /** Featured Description (featureddescription: clobtext) */
  featureddescription?: string;
  /** Feed Description (feeddescription: text) */
  feeddescription?: string;
  /** Feed Name (feedname: text) */
  feedname?: string;
  /** Fixed Lot Size (fixedlotsize: float) */
  fixedlotsize?: number;
  /** Formula (Currency) (formulacurrency: currency) */
  formulacurrency?: number;
  /** Formula (Date) (formuladate: date) */
  formuladate?: Date;
  /** Formula (Date/Time) (formuladatetime: datetime) */
  formuladatetime?: Date;
  /** Formula (Numeric) (formulanumeric: float) */
  formulanumeric?: number;
  /** Formula (Percent) (formulapercent: percent) */
  formulapercent?: number;
  /** Formula (Text) (formulatext: text) */
  formulatext?: string;
  /** Forward Consumption Days (forwardconsumptiondays: integer) */
  forwardconsumptiondays?: number;
  /** Fraud Risk (fraudrisk: select) */
  fraudrisk?: string;
  /** Google Base Product Feed (froogleproductfeed: checkbox) */
  froogleproductfeed?: boolean;
  /** Purchase Price (Foreign Currency) (fxcost: currency2) */
  fxcost?: number;
  /** Gain/Loss Account (gainlossaccount: select) */
  gainlossaccount?: string;
  /** Generate Accruals (generateaccruals: checkbox) */
  generateaccruals?: boolean;
  /** Gift Certificate Auth Code (giftcertauthcode: text) */
  giftcertauthcode?: string;
  /** Gift Certificate To (Email) (giftcertemail: text) */
  giftcertemail?: string;
  /** Gift Certificate Exp Date (giftcertexpirationdate: text) */
  giftcertexpirationdate?: string;
  /** Gift Certificate From (Name) (giftcertfrom: text) */
  giftcertfrom?: string;
  /** Gift Certificate Message (giftcertmessage: text) */
  giftcertmessage?: string;
  /** Gift Certificate Orig Amount (giftcertoriginalamount: text) */
  giftcertoriginalamount?: string;
  /** Gift Certificate To (Name) (giftcertrecipient: text) */
  giftcertrecipient?: string;
  /** # Times Viewed (hits: integer) */
  hits?: number;
  /** Image URL (imageurl: text) */
  imageurl?: string;
  /** Income Account (incomeaccount: select) */
  incomeaccount?: string;
  /** Intercompany Deferred Revenue Account (intercodefrevaccount: select) */
  intercodefrevaccount?: string;
  /** Intercompany Expense/COGS Account (intercoexpenseaccount: select) */
  intercoexpenseaccount?: string;
  /** Intercompany Income Account (intercoincomeaccount: select) */
  intercoincomeaccount?: string;
  /** Internal ID (internalid: select) */
  internalid?: string;
  /** Inventory Location (inventorylocation: select) */
  inventorylocation?: string;
  /** Inventory Classification (invtclassification: text) */
  invtclassification?: string;
  /** Inventory Count Interval (invtcountinterval: integer) */
  invtcountinterval?: number;
  /** Is Available? (isavailable: checkbox) */
  isavailable?: boolean;
  /** Drop Ship Item (isdropshipitem: checkbox) */
  isdropshipitem?: boolean;
  /** Can be Fulfilled (isfulfillable: checkbox) */
  isfulfillable?: boolean;
  /** Google Checkout Compliant (isgcocompliant: checkbox) */
  isgcocompliant?: boolean;
  /** Inactive (isinactive: checkbox) */
  isinactive?: boolean;
  /** Is Lot Numbered Item (islotitem: checkbox) */
  islotitem?: boolean;
  /** Display in Web Site (isonline: checkbox) */
  isonline?: boolean;
  /** Is Serialized Item (isserialitem: checkbox) */
  isserialitem?: boolean;
  /** Special Order Item (isspecialorderitem: checkbox) */
  isspecialorderitem?: boolean;
  /** Special Work Order Item (isspecialworkorderitem: checkbox) */
  isspecialworkorderitem?: boolean;
  /** Store Pickup Allowed (isstorepickupallowed: checkbox) */
  isstorepickupallowed?: boolean;
  /** Product (issueproduct: select) */
  issueproduct?: string;
  /** Taxable (istaxable: checkbox) */
  istaxable?: boolean;
  /** Is VSOE Bundle? (isvsoebundle: checkbox) */
  isvsoebundle?: boolean;
  /** WIP (iswip: checkbox) */
  iswip?: boolean;
  /** Name (itemid: text) */
  itemid?: string;
  /** Item URL (itemurl: text) */
  itemurl?: string;
  /** Last Inventory Count Date (lastinvtcountdate: date) */
  lastinvtcountdate?: Date;
  /** Last Purchase Price (lastpurchaseprice: currency) */
  lastpurchaseprice?: number;
  /** Last Quantity Available Change (lastquantityavailablechange: datetime) */
  lastquantityavailablechange?: Date;
  /** Last Viewed (lastviewed: datetime) */
  lastviewed?: Date;
  /** Lead Time (leadtime: integer) */
  leadtime?: number;
  /** Liability Account (liabilityaccount: select) */
  liabilityaccount?: string;
  /** eBay Duration (listingduration: text) */
  listingduration?: string;
  /** Location (location: select) */
  location?: string;
  /** Location Allow Store Pickup (locationallowstorepickup: checkbox) */
  locationallowstorepickup?: boolean;
  /** Location ATP Lead Time (locationatpleadtime: float) */
  locationatpleadtime?: number;
  /** Location Average Cost (locationaveragecost: currency2) */
  locationaveragecost?: number;
  /** Location Bin Available (locationbinquantityavailable: float) */
  locationbinquantityavailable?: number;
  /** Location Work Order Lead Time (locationbuildtime: float) */
  locationbuildtime?: number;
  /** Location Standard Cost (locationcost: currency) */
  locationcost?: number;
  /** Location Cost Accounting Status (locationcostaccountingstatus: text) */
  locationcostaccountingstatus?: string;
  /** Location Default Return Cost (locationdefaultreturncost: currency2) */
  locationdefaultreturncost?: number;
  /** Location Demand Source (locationdemandsource: text) */
  locationdemandsource?: string;
  /** Location Fixed Lot Size (locationfixedlotsize: float) */
  locationfixedlotsize?: number;
  /** Location Inventory Classification (locationinvtclassification: text) */
  locationinvtclassification?: string;
  /** Location Inventory Count Interval (locationinvtcountinterval: integer) */
  locationinvtcountinterval?: number;
  /** Location Last Inventory Count Date (locationlastinvtcountdate: date) */
  locationlastinvtcountdate?: Date;
  /** Location Lead Time (locationleadtime: integer) */
  locationleadtime?: number;
  /** Location Next Inventory Count Date (locationnextinvtcountdate: date) */
  locationnextinvtcountdate?: Date;
  /** Location (no hierarchy) (locationnohierarchy: select) */
  locationnohierarchy?: string;
  /** Location Preferred Stock Level (locationpreferredstocklevel: float) */
  locationpreferredstocklevel?: number;
  /** Location Available for Store Pickup (locationqtyavailforstorepickup: float) */
  locationqtyavailforstorepickup?: number;
  /** Location Available (locationquantityavailable: float) */
  locationquantityavailable?: number;
  /** Location Back Ordered (locationquantitybackordered: float) */
  locationquantitybackordered?: number;
  /** Location Committed (locationquantitycommitted: float) */
  locationquantitycommitted?: number;
  /** Location In Transit (locationquantityintransit: float) */
  locationquantityintransit?: number;
  /** Location On Hand (locationquantityonhand: float) */
  locationquantityonhand?: number;
  /** Location On Order (locationquantityonorder: float) */
  locationquantityonorder?: number;
  /** Location Reorder Point (locationreorderpoint: float) */
  locationreorderpoint?: number;
  /** Location Safety Stock Level (locationsafetystocklevel: float) */
  locationsafetystocklevel?: number;
  /** Location Store Pickup Buffer Stock (locationstorepickupbufferstock: float) */
  locationstorepickupbufferstock?: number;
  /** Location Supply Lot Sizing Method (locationsupplylotsizingmethod: text) */
  locationsupplylotsizingmethod?: string;
  /** Location Supply Type (locationsupplytype: text) */
  locationsupplytype?: string;
  /** Location Total Value (locationtotalvalue: currency2) */
  locationtotalvalue?: number;
  /** Manufacturer (manufacturer: text) */
  manufacturer?: string;
  /** Manufacturer Address (manufactureraddr1: text) */
  manufactureraddr1?: string;
  /** Manufacturer City (manufacturercity: text) */
  manufacturercity?: string;
  /** Manufacturer State (manufacturerstate: text) */
  manufacturerstate?: string;
  /** Manufacturer Tariff (manufacturertariff: text) */
  manufacturertariff?: string;
  /** Manufacturer Tax Id (manufacturertaxid: text) */
  manufacturertaxid?: string;
  /** Manufacturer Zip (manufacturerzip: text) */
  manufacturerzip?: string;
  /** Match Bill To Receipt (matchbilltoreceipt: checkbox) */
  matchbilltoreceipt?: boolean;
  /** Maximum Quantity (maximumquantity: text) */
  maximumquantity?: string;
  /** Member Item (memberitem: select) */
  memberitem?: string;
  /** Member Quantity (memberquantity: float) */
  memberquantity?: number;
  /** Meta Tag Html (metataghtml: clobtext) */
  metataghtml?: string;
  /** Minimum Quantity (minimumquantity: text) */
  minimumquantity?: string;
  /** Last Modified (modified: datetime) */
  modified?: Date;
  /** MOSS Applies (mossapplies: checkbox) */
  mossapplies?: boolean;
  /** MPN (mpn: text) */
  mpn?: string;
  /** Multiple Manufacture Addresses (multmanufactureaddr: checkbox) */
  multmanufactureaddr?: boolean;
  /** NexTag Category (nextagcategory: text) */
  nextagcategory?: string;
  /** NexTag Product Feed (nextagproductfeed: checkbox) */
  nextagproductfeed?: boolean;
  /** Next Inventory Count Date (nextinvtcountdate: date) */
  nextinvtcountdate?: Date;
  /** No Price Message (nopricemessage: text) */
  nopricemessage?: string;
  /** eBay Active Listings (numactivelistings: integer) */
  numactivelistings?: number;
  /** Number of Allowed Downloads (numberalloweddownloads: text) */
  numberalloweddownloads?: string;
  /** eBay Quantity Currently Listed (numcurrentlylisted: integer) */
  numcurrentlylisted?: number;
  /** Obsolete Date (obsoletedate: date) */
  obsoletedate?: Date;
  /** Obsolete Revision (obsoleterevision: select) */
  obsoleterevision?: string;
  /** Offer Support (offersupport: checkbox) */
  offersupport?: boolean;
  /** Online Customer Price (onlinecustomerprice: currency) */
  onlinecustomerprice?: number;
  /** Online Price (onlineprice: currency) */
  onlineprice?: number;
  /** On Special (onspecial: checkbox) */
  onspecial?: boolean;
  /** Other Prices (otherprices: currency) */
  otherprices?: number;
  /** Vendor (othervendor: select) */
  othervendor?: string;
  /** Out Of Stock Behavior (outofstockbehavior: text) */
  outofstockbehavior?: string;
  /** Out Of Stock Message (outofstockmessage: text) */
  outofstockmessage?: string;
  /** Overall Qty. Pricing Type (overallquantitypricingtype: select) */
  overallquantitypricingtype?: string;
  /** Page Title (pagetitle: textarea) */
  pagetitle?: string;
  /** Parent (parent: select) */
  parent?: string;
  /** Preference Criterion (preferencecriterion: text) */
  preferencecriterion?: string;
  /** Preferred Bin (preferredbin: checkbox) */
  preferredbin?: boolean;
  /** Preferred Location (preferredlocation: select) */
  preferredlocation?: string;
  /** Preferred Stock Level (preferredstocklevel: float) */
  preferredstocklevel?: number;
  /** Days Supply (preferredstockleveldays: integer) */
  preferredstockleveldays?: number;
  /** Prices Include Tax (pricesincludetax: checkbox) */
  pricesincludetax?: boolean;
  /** Pricing Group (pricinggroup: select) */
  pricinggroup?: string;
  /** eBay Category Id (primarycategory: text) */
  primarycategory?: string;
  /** Production Price Variance Account (prodpricevarianceacct: select) */
  prodpricevarianceacct?: string;
  /** Production Quantity Variance Account (prodqtyvarianceacct: select) */
  prodqtyvarianceacct?: string;
  /** Purchase Description (purchasedescription: text) */
  purchasedescription?: string;
  /** Vendor Bill - Purchase Order Amount Tolerance (purchaseorderamount: float) */
  purchaseorderamount?: number;
  /** Vendor Bill - Purchase Order Quantity Tolerance (purchaseorderquantity: float) */
  purchaseorderquantity?: number;
  /** Vendor Bill - Purchase Order Quantity Difference (purchaseorderquantitydiff: float) */
  purchaseorderquantitydiff?: number;
  /** Purchase Price Variance Account (purchasepricevarianceacct: select) */
  purchasepricevarianceacct?: string;
  /** Purchase Unit (purchaseunit: select) */
  purchaseunit?: string;
  /** Available (quantityavailable: float) */
  quantityavailable?: number;
  /** Back Ordered (quantitybackordered: float) */
  quantitybackordered?: number;
  /** Committed (quantitycommitted: float) */
  quantitycommitted?: number;
  /** On Hand (quantityonhand: float) */
  quantityonhand?: number;
  /** On Order (quantityonorder: float) */
  quantityonorder?: number;
  /** Quantity Pricing Schedule (quantitypricingschedule: select) */
  quantitypricingschedule?: string;
  /** Vendor Bill - Item Receipt Amount Tolerance (receiptamount: float) */
  receiptamount?: number;
  /** Vendor Bill - Item Receipt Quantity Tolerance (receiptquantity: float) */
  receiptquantity?: number;
  /** Vendor Bill - Item Receipt Quantity Difference (receiptquantitydiff: float) */
  receiptquantitydiff?: number;
  /** Reorder Multiple (reordermultiple: integer) */
  reordermultiple?: number;
  /** Reorder Point (reorderpoint: float) */
  reorderpoint?: number;
  /** eBay Reserve Price (reserveprice: currency) */
  reserveprice?: number;
  /** Rev Rec Forecast Rule (revrecforecastrule: select) */
  revrecforecastrule?: string;
  /** Foreign Currency Adjustment Account (revreclassfxaccount: select) */
  revreclassfxaccount?: string;
  /** Rev. Rec. Schedule (revrecschedule: select) */
  revrecschedule?: string;
  /** Round Up Quantity as Component (roundupascomponent: checkbox) */
  roundupascomponent?: boolean;
  /** Safety Stock Level (safetystocklevel: float) */
  safetystocklevel?: number;
  /** Safety Stock Days (safetystockleveldays: integer) */
  safetystockleveldays?: number;
  /** Description (salesdescription: text) */
  salesdescription?: string;
  /** Tax Code (salestaxcode: select) */
  salestaxcode?: string;
  /** Sale Unit (saleunit: select) */
  saleunit?: string;
  /** Same as Primary Book Amortization (sameasprimarybookamortization: checkbox) */
  sameasprimarybookamortization?: boolean;
  /** Same as Primary Book Rev. Rec. (sameasprimarybookrevrec: checkbox) */
  sameasprimarybookrevrec?: boolean;
  /** Schedule B Code (schedulebcode: text) */
  schedulebcode?: string;
  /** Schedule B Number (schedulebnumber: text) */
  schedulebnumber?: string;
  /** Schedule B Quantity (schedulebquantity: text) */
  schedulebquantity?: string;
  /** Scrap Account (scrapacct: select) */
  scrapacct?: string;
  /** Search Keywords (searchkeywords: text) */
  searchkeywords?: string;
  /** Seasonal Demand (seasonaldemand: checkbox) */
  seasonaldemand?: boolean;
  /** eBay Auction (sellonebay: checkbox) */
  sellonebay?: boolean;
  /** Serial/Lot Number (serialnumber: text) */
  serialnumber?: string;
  /** Serial/Lot Number Location (serialnumberlocation: text) */
  serialnumberlocation?: string;
  /** Ships Individually (shipindividually: checkbox) */
  shipindividually?: boolean;
  /** Shipping Package (shippackage: select) */
  shippackage?: string;
  /** Shipping Rate (shippingrate: currency) */
  shippingrate?: number;
  /** Shopping.com Category (shoppingdotcomcategory: text) */
  shoppingdotcomcategory?: string;
  /** Shopping.com Product Feed (shoppingproductfeed: checkbox) */
  shoppingproductfeed?: boolean;
  /** Shopzilla Category Id (shopzillacategoryid: integer) */
  shopzillacategoryid?: number;
  /** Shopzilla Product Feed (shopzillaproductfeed: checkbox) */
  shopzillaproductfeed?: boolean;
  /** Sitemap Priority (sitemappriority: float) */
  sitemappriority?: number;
  /** Soft Descriptor (softdescriptor: select) */
  softdescriptor?: string;
  /** eBay Starting Price (startingprice: currency) */
  startingprice?: number;
  /** Stock Description (stockdescription: text) */
  stockdescription?: string;
  /** Stock Unit (stockunit: select) */
  stockunit?: string;
  /** Store Description (storedescription: text) */
  storedescription?: string;
  /** Detailed Description (storedetaileddescription: clobtext) */
  storedetaileddescription?: string;
  /** Store Display Image (storedisplayimage: select) */
  storedisplayimage?: string;
  /** Store Display Name (storedisplayname: text) */
  storedisplayname?: string;
  /** Store Display Thumbnail (storedisplaythumbnail: select) */
  storedisplaythumbnail?: string;
  /** Subsidiary (subsidiary: select) */
  subsidiary?: string;
  /** Subsidiary (no hierarchy) (subsidiarynohierarchy: select) */
  subsidiarynohierarchy?: string;
  /** SubType (subtype: text) */
  subtype?: string;
  /** Supply Lot Sizing Method (supplylotsizingmethod: text) */
  supplylotsizingmethod?: string;
  /** Replenishment Method (supplyreplenishmentmethod: text) */
  supplyreplenishmentmethod?: string;
  /** Supply Type (supplytype: text) */
  supplytype?: string;
  /** Tax Schedule (taxschedule: select) */
  taxschedule?: string;
  /** Thumbnail URL (thumbnailurl: text) */
  thumbnailurl?: string;
  /** Total Value (totalvalue: currency2) */
  totalvalue?: number;
  /** Track Landed Cost (tracklandedcost: checkbox) */
  tracklandedcost?: boolean;
  /** Transfer Price (transferprice: currency2) */
  transferprice?: number;
  /** Type (type: select) */
  type?: string;
  /** Unbuild Variance Account (unbuildvarianceaccount: select) */
  unbuildvarianceaccount?: string;
  /** Units Type (unitstype: select) */
  unitstype?: string;
  /** UPC Code (upccode: text) */
  upccode?: string;
  /** URL Component (urlcomponent: text) */
  urlcomponent?: string;
  /** Use Bins (usebins: checkbox) */
  usebins?: boolean;
  /** Use Component Yield (usecomponentyield: checkbox) */
  usecomponentyield?: boolean;
  /** Use Marginal Rates (usemarginalrates: checkbox) */
  usemarginalrates?: boolean;
  /** Preferred Vendor (vendor: select) */
  vendor?: string;
  /** Vendor Code (vendorcode: text) */
  vendorcode?: string;
  /** Vendor Price (vendorcost: currency) */
  vendorcost?: number;
  /** Vendor Price (Entered) (vendorcostentered: currency) */
  vendorcostentered?: number;
  /** Vendor Name (vendorname: text) */
  vendorname?: string;
  /** Vendor Price Currency (vendorpricecurrency: text) */
  vendorpricecurrency?: string;
  /** Vendor Schedule (vendorschedule: select) */
  vendorschedule?: string;
  /** Vendor Return Variance Account (vendreturnvarianceaccount: select) */
  vendreturnvarianceaccount?: string;
  /** Deferral (vsoedeferral: select) */
  vsoedeferral?: string;
  /** Default as Delivered (vsoedelivered: checkbox) */
  vsoedelivered?: boolean;
  /** Permit Discount (vsoepermitdiscount: select) */
  vsoepermitdiscount?: string;
  /** VSOE Price (vsoeprice: currency2) */
  vsoeprice?: number;
  /** Allocation Type (vsoesopgroup: checkbox) */
  vsoesopgroup?: boolean;
  /** Web Site (website: select) */
  website?: string;
  /** Weight (weight: float) */
  weight?: number;
  /** Weight Units (weightunit: select) */
  weightunit?: string;
  /** WIP Account (wipacct: select) */
  wipacct?: string;
  /** WIP Cost Variance Account (wipvarianceacct: select) */
  wipvarianceacct?: string;
  /** Yahoo Shopping Product Feed (yahooproductfeed: checkbox) */
  yahooproductfeed?: boolean;
}


// Search Filters

/** Item (item) Search Filters definition */
export interface itemSearchFilter {/** Accounting Book Rev Rec Forecast Rule (accbookrevrecforecastrule: select) */
  accbookrevrecforecastrule?: string;
  /** Account (account: select) */
  account?: string;
  /** Accounting Book (accountingbook: select) */
  accountingbook?: string;
  /** Accounting Book Amortization Schedule (accountingbookamortization: select) */
  accountingbookamortization?: string;
  /** Accounting Book Create Revenue Plans On (accountingbookcreateplanson: select) */
  accountingbookcreateplanson?: string;
  /** Accounting Book Revenue Recognition Rule (accountingbookrevrecrule: select) */
  accountingbookrevrecrule?: string;
  /** Accounting Book Rev. Rec. Schedule (accountingbookrevrecschedule: select) */
  accountingbookrevrecschedule?: string;
  /** Alternate Source Item (alternatedemandsourceitem: select) */
  alternatedemandsourceitem?: string;
  /** ATP Lead Time (atpleadtime: float) */
  atpleadtime?: number;
  /** Default ATP Method (atpmethod: select) */
  atpmethod?: string;
  /** Auto-Calculate Lead Time (autoleadtime: checkbox) */
  autoleadtime?: boolean;
  /** Auto-Calculate Preferred Stock Level (autopreferredstocklevel: checkbox) */
  autopreferredstocklevel?: boolean;
  /** Auto-Calculate Reorder Point (autoreorderpoint: checkbox) */
  autoreorderpoint?: boolean;
  /** Available to Partners (availabletopartners: checkbox) */
  availabletopartners?: boolean;
  /** Average Cost (averagecost: currency) */
  averagecost?: number;
  /** Backward Consumption Days (backwardconsumptiondays: integer) */
  backwardconsumptiondays?: number;
  /** Bin Number (binnumber: text) */
  binnumber?: string;
  /** Bin On Hand Available (binonhandavail: float) */
  binonhandavail?: number;
  /** Bin On Hand Count (binonhandcount: float) */
  binonhandcount?: number;
  /** BOM Quantity (bomquantity: float) */
  bomquantity?: number;
  /** Build Sub-Assemblies (buildentireassembly: checkbox) */
  buildentireassembly?: boolean;
  /** Work Order Lead Time (buildtime: float) */
  buildtime?: number;
  /** eBay Buy It Now Price (buyitnowprice: currency) */
  buyitnowprice?: number;
  /** Store Display Name (caption: text) */
  caption?: string;
  /** Category (category: multiselect) */
  category?: number;
  /** Class (class: select) */
  class?: string;
  /** Component Item (component: select) */
  component?: string;
  /** Component Of (componentof: select) */
  componentof?: string;
  /** Component Yield (componentyield: float) */
  componentyield?: number;
  /** Eligible For Contingent Revenue Handling (contingentrevenuehandling: checkbox) */
  contingentrevenuehandling?: boolean;
  /** Copy SO Descr. (copydescription: checkbox) */
  copydescription?: boolean;
  /** Correlated Item (correlateditem: select) */
  correlateditem?: string;
  /** Correlated Item Correlation (correlateditemcorrelation: float) */
  correlateditemcorrelation?: number;
  /** Correlated Item Count (correlateditemcount: integer) */
  correlateditemcount?: number;
  /** Correlated Item Lift (correlateditemlift: float) */
  correlateditemlift?: number;
  /** Correlated Item PurchaseRate (correlateditempurchaserate: float) */
  correlateditempurchaserate?: number;
  /** Purchase Price (cost: currency) */
  cost?: number;
  /** Cost Accounting Status (costaccountingstatus: select) */
  costaccountingstatus?: string;
  /** Cost Category (costcategory: select) */
  costcategory?: string;
  /** Item Defined Cost (costestimate: float) */
  costestimate?: number;
  /** Cost Estimate Type (costestimatetype: select) */
  costestimatetype?: string;
  /** Costing Method (costingmethod: select) */
  costingmethod?: string;
  /** Manufacturer Country (countryofmanufacture: select) */
  countryofmanufacture?: string;
  /** Date Created (created: datetime) */
  created?: Date;
  /** Create Job (createjob: checkbox) */
  createjob?: boolean;
  /** Create Revenue Plans On (createrevenueplanson: select) */
  createrevenueplanson?: string;
  /** Current Standard Cost (currentstandardcost: currency) */
  currentstandardcost?: number;
  /** Current Standard Cost Effective Date (currentstdcosteffectivedate: date) */
  currentstdcosteffectivedate?: Date;
  /** Date Viewed (dateviewed: datetime) */
  dateviewed?: Date;
  /** Days Before Expiration (daysbeforeexpiration: float) */
  daysbeforeexpiration?: number;
  /** Default Return Cost (defaultreturncost: currency) */
  defaultreturncost?: number;
  /** Hold Revenue Recognition (deferrevrec: checkbox) */
  deferrevrec?: boolean;
  /** Estimated Demand Change (demandmodifier: percent) */
  demandmodifier?: number;
  /** Demand Source (demandsource: select) */
  demandsource?: string;
  /** Department (department: select) */
  department?: string;
  /** Direct Revenue Posting (directrevenueposting: checkbox) */
  directrevenueposting?: boolean;
  /** eBay Store (displayinebaystore: checkbox) */
  displayinebaystore?: boolean;
  /** Display Name (displayname: text) */
  displayname?: string;
  /** Distribution Category (distributioncategory: select) */
  distributioncategory?: string;
  /** Distribution Network (distributionnetwork: select) */
  distributionnetwork?: string;
  /** Don't Show Price (dontshowprice: checkbox) */
  dontshowprice?: boolean;
  /** eBay Description (ebayitemdescription: clobtext) */
  ebayitemdescription?: string;
  /** eBay Subtitle (ebayitemsubtitle: text) */
  ebayitemsubtitle?: string;
  /** eBay Title (ebayitemtitle: text) */
  ebayitemtitle?: string;
  /** eBay Relisting Option (ebayrelistingoption: select) */
  ebayrelistingoption?: string;
  /** Effective BOM Control (effectivebomcontrol: select) */
  effectivebomcontrol?: string;
  /** Effective Date (effectivedate: date) */
  effectivedate?: Date;
  /** Effective Revision (effectiverevision: select) */
  effectiverevision?: string;
  /** eBay End Auctions When Out of Stock (endauctionswhenoutofstock: checkbox) */
  endauctionswhenoutofstock?: boolean;
  /** Exclude From Sitemap (excludefromsitemap: checkbox) */
  excludefromsitemap?: boolean;
  /** External ID (externalid: select) */
  externalid?: string;
  /** External ID (Text) (externalidstring: text) */
  externalidstring?: string;
  /** Featured Description (featureddescription: clobtext) */
  featureddescription?: string;
  /** Feed Description (feeddescription: clobtext) */
  feeddescription?: string;
  /** Feed Name (feedname: text) */
  feedname?: string;
  /** Fixed Lot Size (fixedlotsize: float) */
  fixedlotsize?: number;
  /** Formula (Date) (formuladate: date) */
  formuladate?: Date;
  /** Formula (Numeric) (formulanumeric: float) */
  formulanumeric?: number;
  /** Formula (Text) (formulatext: text) */
  formulatext?: string;
  /** Forward Consumption Days (forwardconsumptiondays: integer) */
  forwardconsumptiondays?: number;
  /** Fraud Risk (fraudrisk: select) */
  fraudrisk?: string;
  /** Google Base Product Feed (froogleproductfeed: checkbox) */
  froogleproductfeed?: boolean;
  /** Purchase Price (Foreign Currency) (fxcost: currency) */
  fxcost?: number;
  /** Generate Accruals (generateaccruals: checkbox) */
  generateaccruals?: boolean;
  /** Gift Certificate Code (giftcertauthcode: text) */
  giftcertauthcode?: string;
  /** Gift Certificate To (Email) (giftcertemail: text) */
  giftcertemail?: string;
  /** Gift Certificate Expiration Date (giftcertexpdate: date) */
  giftcertexpdate?: Date;
  /** Gift Certificate From (Name) (giftcertfrom: text) */
  giftcertfrom?: string;
  /** Gift Certificate Message (giftcertmsg: text) */
  giftcertmsg?: string;
  /** Gift Certificate Original Amount (giftcertorigamt: text) */
  giftcertorigamt?: string;
  /** Gift Certificate To (Name) (giftcertrecipient: text) */
  giftcertrecipient?: string;
  /** Image URL (imageurl: text) */
  imageurl?: string;
  /** Internal ID (internalid: select) */
  internalid?: string;
  /** Internal ID (Number) (internalidnumber: integer) */
  internalidnumber?: number;
  /** Inventory Location (inventorylocation: select) */
  inventorylocation?: string;
  /** Inventory Classification (invtclassification: select) */
  invtclassification?: string;
  /** Inventory Count Interval (invtcountinterval: integer) */
  invtcountinterval?: number;
  /** Is Available? (isavailable: checkbox) */
  isavailable?: boolean;
  /** Drop Ship Item (isdropshipitem: checkbox) */
  isdropshipitem?: boolean;
  /** Can be Fulfilled (isfulfillable: checkbox) */
  isfulfillable?: boolean;
  /** Google Checkout Compliant (isgcocompliant: checkbox) */
  isgcocompliant?: boolean;
  /** Inactive (isinactive: checkbox) */
  isinactive?: boolean;
  /** Is Lot Numbered Item (islotitem: checkbox) */
  islotitem?: boolean;
  /** Display in Web Site (isonline: checkbox) */
  isonline?: boolean;
  /** Vendor is Preferred (ispreferredvendor: checkbox) */
  ispreferredvendor?: boolean;
  /** Is Serialized Item (isserialitem: checkbox) */
  isserialitem?: boolean;
  /** Special Order Item (isspecialorderitem: checkbox) */
  isspecialorderitem?: boolean;
  /** Special Work Order Item (isspecialworkorderitem: checkbox) */
  isspecialworkorderitem?: boolean;
  /** Store Pickup Allowed (isstorepickupallowed: checkbox) */
  isstorepickupallowed?: boolean;
  /** Product (issueproduct: select) */
  issueproduct?: string;
  /** Taxable (istaxable: checkbox) */
  istaxable?: boolean;
  /** Is VSOE Bundle? (isvsoebundle: checkbox) */
  isvsoebundle?: boolean;
  /** WIP (iswip: checkbox) */
  iswip?: boolean;
  /** Name (Internal) (itemid: text) */
  itemid?: string;
  /** Item URL (itemurl: text) */
  itemurl?: string;
  /** Last Inventory Count Date (lastinvtcountdate: date) */
  lastinvtcountdate?: Date;
  /** Last Modified (lastmodifieddate: datetime) */
  lastmodifieddate?: Date;
  /** Last Purchase Price (lastpurchaseprice: currency) */
  lastpurchaseprice?: number;
  /** Last Quantity Available Change (lastquantityavailablechange: datetime) */
  lastquantityavailablechange?: Date;
  /** Lead Time (leadtime: integer) */
  leadtime?: number;
  /** eBay Duration (listingduration: select) */
  listingduration?: string;
  /** Location (location: select) */
  location?: string;
  /** Location Allow Store Pickup (locationallowstorepickup: checkbox) */
  locationallowstorepickup?: boolean;
  /** Location ATP Lead Time (locationatpleadtime: float) */
  locationatpleadtime?: number;
  /** Location Average Cost (locationaveragecost: currency) */
  locationaveragecost?: number;
  /** Location Work Order Lead Time (locationbuildtime: float) */
  locationbuildtime?: number;
  /** Location Standard Cost (locationcost: currency) */
  locationcost?: number;
  /** Location Cost Accounting Status (locationcostaccountingstatus: select) */
  locationcostaccountingstatus?: string;
  /** Location Default Return Cost (locationdefaultreturncost: currency) */
  locationdefaultreturncost?: number;
  /** Location Demand Source (locationdemandsource: select) */
  locationdemandsource?: string;
  /** Location Fixed Lot Size (locationfixedlotsize: float) */
  locationfixedlotsize?: number;
  /** Location Inventory Classification (locationinvtclassification: select) */
  locationinvtclassification?: string;
  /** Location Inventory Count Interval (locationinvtcountinterval: integer) */
  locationinvtcountinterval?: number;
  /** Location Last Inventory Count Date (locationlastinvtcountdate: date) */
  locationlastinvtcountdate?: Date;
  /** Location Lead Time (locationleadtime: integer) */
  locationleadtime?: number;
  /** Location Next Inventory Count Date (locationnextinvtcountdate: date) */
  locationnextinvtcountdate?: Date;
  /** Location Preferred Stock Level (locationpreferredstocklevel: float) */
  locationpreferredstocklevel?: number;
  /** Location Available for Store Pickup (locationqtyavailforstorepickup: float) */
  locationqtyavailforstorepickup?: number;
  /** Location Available (locationquantityavailable: float) */
  locationquantityavailable?: number;
  /** Location Back Ordered (locationquantitybackordered: float) */
  locationquantitybackordered?: number;
  /** Location Committed (locationquantitycommitted: float) */
  locationquantitycommitted?: number;
  /** Location In Transit (locationquantityintransit: float) */
  locationquantityintransit?: number;
  /** Location On Hand (locationquantityonhand: float) */
  locationquantityonhand?: number;
  /** Location On Order (locationquantityonorder: float) */
  locationquantityonorder?: number;
  /** Location Reorder Point (locationreorderpoint: float) */
  locationreorderpoint?: number;
  /** Location Safety Stock Level (locationsafetystocklevel: float) */
  locationsafetystocklevel?: number;
  /** Location Store Pickup Buffer Stock (locationstorepickupbufferstock: float) */
  locationstorepickupbufferstock?: number;
  /** Location Supply Lot Sizing Method (locationsupplylotsizingmethod: select) */
  locationsupplylotsizingmethod?: string;
  /** Location Supply Type (locationsupplytype: select) */
  locationsupplytype?: string;
  /** Location Total Value (locationtotalvalue: currency) */
  locationtotalvalue?: number;
  /** Manufacturer (manufacturer: text) */
  manufacturer?: string;
  /** Manufacturer Address (manufactureraddr1: text) */
  manufactureraddr1?: string;
  /** Manufacturer City (manufacturercity: text) */
  manufacturercity?: string;
  /** Manufacturer State (manufacturerstate: text) */
  manufacturerstate?: string;
  /** Manufacturer Tariff (manufacturertariff: text) */
  manufacturertariff?: string;
  /** Manufacturer Tax Id (manufacturertaxid: text) */
  manufacturertaxid?: string;
  /** Manufacturer Zip (manufacturerzip: text) */
  manufacturerzip?: string;
  /** Match Bill To Receipt (matchbilltoreceipt: checkbox) */
  matchbilltoreceipt?: boolean;
  /** Matrix Item (matrix: checkbox) */
  matrix?: boolean;
  /** Matrix Child Item (matrixchild: checkbox) */
  matrixchild?: boolean;
  /** Maximum Quantity (maximumquantity: integer) */
  maximumquantity?: number;
  /** Meta Tag Html (metataghtml: clobtext) */
  metataghtml?: string;
  /** Minimum Quantity (minimumquantity: integer) */
  minimumquantity?: number;
  /** MOSS Applies (mossapplies: checkbox) */
  mossapplies?: boolean;
  /** MPN (mpn: text) */
  mpn?: string;
  /** Multiple Manufacture Addresses (multmanufactureaddr: checkbox) */
  multmanufactureaddr?: boolean;
  /** NexTag Category (nextagcategory: text) */
  nextagcategory?: string;
  /** NexTag Product Feed (nextagproductfeed: checkbox) */
  nextagproductfeed?: boolean;
  /** Next Inventory Count Date (nextinvtcountdate: date) */
  nextinvtcountdate?: Date;
  /** eBay Active Listings (numactivelistings: integer) */
  numactivelistings?: number;
  /** Number of Allowed Downloads (numberalloweddownloads: float) */
  numberalloweddownloads?: number;
  /** eBay Quantity Currently Listed (numcurrentlylisted: integer) */
  numcurrentlylisted?: number;
  /** Obsolete Date (obsoletedate: date) */
  obsoletedate?: Date;
  /** Obsolete Revision (obsoleterevision: select) */
  obsoleterevision?: string;
  /** Offer Support (offersupport: checkbox) */
  offersupport?: boolean;
  /** Online Customer Price (onlinecustomerprice: currency) */
  onlinecustomerprice?: number;
  /** On Special (onspecial: checkbox) */
  onspecial?: boolean;
  /** Vendor (othervendor: select) */
  othervendor?: string;
  /** Out Of Stock Behavior (outofstockbehavior: select) */
  outofstockbehavior?: string;
  /** Overall Qty. Pricing Type (overallquantitypricingtype: select) */
  overallquantitypricingtype?: string;
  /** Page Title (pagetitle: text) */
  pagetitle?: string;
  /** Sub-Item Of (parent: select) */
  parent?: string;
  /** Preference Criterion (preferencecriterion: text) */
  preferencecriterion?: string;
  /** Preferred Bin (preferredbin: checkbox) */
  preferredbin?: boolean;
  /** Preferred Location (preferredlocation: select) */
  preferredlocation?: string;
  /** Preferred Stock Level (preferredstocklevel: float) */
  preferredstocklevel?: number;
  /** Preferred Stock Level Days (preferredstockleveldays: integer) */
  preferredstockleveldays?: number;
  /** Sales Price (price: currency) */
  price?: number;
  /** Prices Include Tax (pricesincludetax: checkbox) */
  pricesincludetax?: boolean;
  /** Pricing Group (pricinggroup: select) */
  pricinggroup?: string;
  /** eBay Category Id (primarycategory: integer) */
  primarycategory?: number;
  /** Vendor Bill - Purchase Order Amount Tolerance (purchaseorderamount: float) */
  purchaseorderamount?: number;
  /** Vendor Bill - Purchase Order Quantity Tolerance (purchaseorderquantity: float) */
  purchaseorderquantity?: number;
  /** Vendor Bill - Purchase Order Quantity Difference (purchaseorderquantitydiff: float) */
  purchaseorderquantitydiff?: number;
  /** Purchase Unit (purchaseunit: select) */
  purchaseunit?: string;
  /** Available (quantityavailable: float) */
  quantityavailable?: number;
  /** Back Ordered (quantitybackordered: float) */
  quantitybackordered?: number;
  /** Committed (quantitycommitted: float) */
  quantitycommitted?: number;
  /** On Hand (quantityonhand: float) */
  quantityonhand?: number;
  /** On Order (quantityonorder: float) */
  quantityonorder?: number;
  /** Qty. Pricing Schedule (quantitypricingschedule: select) */
  quantitypricingschedule?: string;
  /** Vendor Bill - Item Receipt Amount Tolerance (receiptamount: float) */
  receiptamount?: number;
  /** Vendor Bill - Item Receipt Quantity Tolerance (receiptquantity: float) */
  receiptquantity?: number;
  /** Vendor Bill - Item Receipt Quantity Difference (receiptquantitydiff: float) */
  receiptquantitydiff?: number;
  /** Reorder Multiple (reordermultiple: integer) */
  reordermultiple?: number;
  /** Reorder Point (reorderpoint: float) */
  reorderpoint?: number;
  /** eBay Reserve Price (reserveprice: currency) */
  reserveprice?: number;
  /** Rev Rec Forecast Rule (revrecforecastrule: select) */
  revrecforecastrule?: string;
  /** Rev. Rec. Schedule (revrecschedule: select) */
  revrecschedule?: string;
  /** Safety Stock Level (safetystocklevel: float) */
  safetystocklevel?: number;
  /** Safety Stock Level Days (safetystockleveldays: integer) */
  safetystockleveldays?: number;
  /** Description (salesdescription: text) */
  salesdescription?: string;
  /** Sale Unit (saleunit: select) */
  saleunit?: string;
  /** Same as Primary Book Amortization (sameasprimarybookamortization: checkbox) */
  sameasprimarybookamortization?: boolean;
  /** Same as Primary Book Rev. Rec. (sameasprimarybookrevrec: checkbox) */
  sameasprimarybookrevrec?: boolean;
  /** Schedule B Code (schedulebcode: select) */
  schedulebcode?: string;
  /** Schedule B Number (schedulebnumber: text) */
  schedulebnumber?: string;
  /** Schedule B Quantity (schedulebquantity: text) */
  schedulebquantity?: string;
  /** Search Keywords (searchkeywords: text) */
  searchkeywords?: string;
  /** Seasonal Demand (seasonaldemand: checkbox) */
  seasonaldemand?: boolean;
  /** eBay Auction (sellonebay: checkbox) */
  sellonebay?: boolean;
  /** Serial/Lot Number (serialnumber: text) */
  serialnumber?: string;
  /** Serial/Lot Number Location (serialnumberlocation: select) */
  serialnumberlocation?: string;
  /** Ships Individually (shipindividually: checkbox) */
  shipindividually?: boolean;
  /** Shipping Package (shippackage: select) */
  shippackage?: string;
  /** Shipping Rate (shippingrate: currency) */
  shippingrate?: number;
  /** Shopping Category (shoppingdotcomcategory: text) */
  shoppingdotcomcategory?: string;
  /** Shopping Product Feed (shoppingproductfeed: checkbox) */
  shoppingproductfeed?: boolean;
  /** Shopzilla Category Id (shopzillacategoryid: integer) */
  shopzillacategoryid?: number;
  /** Shopzilla Product Feed (shopzillaproductfeed: checkbox) */
  shopzillaproductfeed?: boolean;
  /** Sitemap Priority (sitemappriority: float) */
  sitemappriority?: number;
  /** Soft Descriptor (softdescriptor: select) */
  softdescriptor?: string;
  /** eBay Starting Price (startingprice: currency) */
  startingprice?: number;
  /** Stock Description (stockdescription: text) */
  stockdescription?: string;
  /** Stock Unit (stockunit: select) */
  stockunit?: string;
  /** Store Description (storedescription: clobtext) */
  storedescription?: string;
  /** Subsidiary (subsidiary: select) */
  subsidiary?: string;
  /** Sub Type (subtype: select) */
  subtype?: string;
  /** Supply Lot Sizing Method (supplylotsizingmethod: select) */
  supplylotsizingmethod?: string;
  /** Replenishment Method (supplyreplenishmentmethod: select) */
  supplyreplenishmentmethod?: string;
  /** Supply Type (supplytype: select) */
  supplytype?: string;
  /** Tax Code (taxcode: select) */
  taxcode?: string;
  /** Tax Schedule (taxschedule: select) */
  taxschedule?: string;
  /** Thumbnail URL (thumbnailurl: text) */
  thumbnailurl?: string;
  /** Total Value (totalvalue: currency) */
  totalvalue?: number;
  /** Track Landed Cost (tracklandedcost: checkbox) */
  tracklandedcost?: boolean;
  /** Transfer Price (transferprice: float) */
  transferprice?: number;
  /** Type (type: select) */
  type?: string;
  /** Units Type (unitstype: select) */
  unitstype?: string;
  /** UPC Code (upccode: text) */
  upccode?: string;
  /** URL Component (urlcomponent: text) */
  urlcomponent?: string;
  /** Use Bins (usebins: checkbox) */
  usebins?: boolean;
  /** Use Component Yield (usecomponentyield: checkbox) */
  usecomponentyield?: boolean;
  /** Use Marginal Rates (usemarginalrates: checkbox) */
  usemarginalrates?: boolean;
  /** Preferred Vendor (vendor: select) */
  vendor?: string;
  /** Vendor Code (vendorcode: text) */
  vendorcode?: string;
  /** Vendor Price (vendorcost: currency) */
  vendorcost?: number;
  /** Vendor Price (Entered) (vendorcostentered: currency) */
  vendorcostentered?: number;
  /** Vendor Name (vendorname: text) */
  vendorname?: string;
  /** Vendor Price Currency (vendorpricecurrency: select) */
  vendorpricecurrency?: string;
  /** Deferral (vsoedeferral: select) */
  vsoedeferral?: string;
  /** Default as Delivered (vsoedelivered: checkbox) */
  vsoedelivered?: boolean;
  /** Permit Discount (vsoepermitdiscount: select) */
  vsoepermitdiscount?: string;
  /** VSOE Price (vsoeprice: float) */
  vsoeprice?: number;
  /** Allocation Type (vsoesopgroup: select) */
  vsoesopgroup?: string;
  /** Web Site (website: select) */
  website?: string;
  /** Weight (weight: float) */
  weight?: number;
  /** Yahoo Shopping Product Feed (yahooproductfeed: checkbox) */
  yahooproductfeed?: boolean;
}


// Search Joins

/** Item (item) Search Joins definitions. */
export interface itemSearchJoin {/** item's assemblyitembillofmaterials search filter. Assembly Item Bill of Materials. Actual name: Assembly Item Bill of Materials. */
  assemblyitembillofmaterials: 'assemblyitembillofmaterials';
  /** item's binonhand search filter. Bin On Hand. Actual name: Item Bin Number. */
  binonhand: 'binonhand';
  /** item's effectiverevision search filter. Effective Revision. Actual name: Item Revision. */
  effectiverevision: 'effectiverevision';
  /** item's inventorydetail search filter. Inventory Detail. Actual name: Inventory Detail. */
  inventorydetail: 'inventorydetail';
  /** item's inventorylocation search filter. Inventory Location. Actual name: Location. */
  inventorylocation: 'inventorylocation';
  /** item's inventorynumber search filter. Inventory Number. Actual name: Inventory Numbers. */
  inventorynumber: 'inventorynumber';
  /** item's inventorynumberbinonhand search filter. Inventory Number/Bin on Hand. Actual name: Inventory Number Bin. */
  inventorynumberbinonhand: 'inventorynumberbinonhand';
  /** item's obsoleterevision search filter. Obsolete Revision. Actual name: Item Revision. */
  obsoleterevision: 'obsoleterevision';
  /** item's preferredlocation search filter. Preferred Location. Actual name: Location. */
  preferredlocation: 'preferredlocation';
  /** item's preferredvendor search filter. Preferred Vendor. Actual name: Vendor. */
  preferredvendor: 'preferredvendor';
  /** item's pricing search filter. Pricing. Actual name: Pricing. */
  pricing: 'pricing';
  /** item's shopper search filter. Shopper. Actual name: Customer. */
  shopper: 'shopper';
  /** item's user search filter. User. Actual name: Employee. */
  user: 'user';
  /** item's vendor search filter. Vendor. Actual name: Vendor. */
  vendor: 'vendor';
}


// Search Filter Types

/** Item (item) Search Filter Type definitions. */
export interface itemSearchFilterTypes {accbookrevrecforecastrule: 'select';
  account: 'select';
  accountingbook: 'select';
  accountingbookamortization: 'select';
  accountingbookcreateplanson: 'select';
  accountingbookrevrecrule: 'select';
  accountingbookrevrecschedule: 'select';
  alternatedemandsourceitem: 'select';
  atpleadtime: 'float';
  atpmethod: 'select';
  autoleadtime: 'checkbox';
  autopreferredstocklevel: 'checkbox';
  autoreorderpoint: 'checkbox';
  availabletopartners: 'checkbox';
  averagecost: 'currency';
  backwardconsumptiondays: 'integer';
  binnumber: 'text';
  binonhandavail: 'float';
  binonhandcount: 'float';
  bomquantity: 'float';
  buildentireassembly: 'checkbox';
  buildtime: 'float';
  buyitnowprice: 'currency';
  caption: 'text';
  category: 'multiselect';
  class: 'select';
  component: 'select';
  componentof: 'select';
  componentyield: 'float';
  contingentrevenuehandling: 'checkbox';
  copydescription: 'checkbox';
  correlateditem: 'select';
  correlateditemcorrelation: 'float';
  correlateditemcount: 'integer';
  correlateditemlift: 'float';
  correlateditempurchaserate: 'float';
  cost: 'currency';
  costaccountingstatus: 'select';
  costcategory: 'select';
  costestimate: 'float';
  costestimatetype: 'select';
  costingmethod: 'select';
  countryofmanufacture: 'select';
  created: 'datetime';
  createjob: 'checkbox';
  createrevenueplanson: 'select';
  currentstandardcost: 'currency';
  currentstdcosteffectivedate: 'date';
  dateviewed: 'datetime';
  daysbeforeexpiration: 'float';
  defaultreturncost: 'currency';
  deferrevrec: 'checkbox';
  demandmodifier: 'percent';
  demandsource: 'select';
  department: 'select';
  directrevenueposting: 'checkbox';
  displayinebaystore: 'checkbox';
  displayname: 'text';
  distributioncategory: 'select';
  distributionnetwork: 'select';
  dontshowprice: 'checkbox';
  ebayitemdescription: 'clobtext';
  ebayitemsubtitle: 'text';
  ebayitemtitle: 'text';
  ebayrelistingoption: 'select';
  effectivebomcontrol: 'select';
  effectivedate: 'date';
  effectiverevision: 'select';
  endauctionswhenoutofstock: 'checkbox';
  excludefromsitemap: 'checkbox';
  externalid: 'select';
  externalidstring: 'text';
  featureddescription: 'clobtext';
  feeddescription: 'clobtext';
  feedname: 'text';
  fixedlotsize: 'float';
  formuladate: 'date';
  formulanumeric: 'float';
  formulatext: 'text';
  forwardconsumptiondays: 'integer';
  fraudrisk: 'select';
  froogleproductfeed: 'checkbox';
  fxcost: 'currency';
  generateaccruals: 'checkbox';
  giftcertauthcode: 'text';
  giftcertemail: 'text';
  giftcertexpdate: 'date';
  giftcertfrom: 'text';
  giftcertmsg: 'text';
  giftcertorigamt: 'text';
  giftcertrecipient: 'text';
  imageurl: 'text';
  internalid: 'select';
  internalidnumber: 'integer';
  inventorylocation: 'select';
  invtclassification: 'select';
  invtcountinterval: 'integer';
  isavailable: 'checkbox';
  isdropshipitem: 'checkbox';
  isfulfillable: 'checkbox';
  isgcocompliant: 'checkbox';
  isinactive: 'checkbox';
  islotitem: 'checkbox';
  isonline: 'checkbox';
  ispreferredvendor: 'checkbox';
  isserialitem: 'checkbox';
  isspecialorderitem: 'checkbox';
  isspecialworkorderitem: 'checkbox';
  isstorepickupallowed: 'checkbox';
  issueproduct: 'select';
  istaxable: 'checkbox';
  isvsoebundle: 'checkbox';
  iswip: 'checkbox';
  itemid: 'text';
  itemurl: 'text';
  lastinvtcountdate: 'date';
  lastmodifieddate: 'datetime';
  lastpurchaseprice: 'currency';
  lastquantityavailablechange: 'datetime';
  leadtime: 'integer';
  listingduration: 'select';
  location: 'select';
  locationallowstorepickup: 'checkbox';
  locationatpleadtime: 'float';
  locationaveragecost: 'currency';
  locationbuildtime: 'float';
  locationcost: 'currency';
  locationcostaccountingstatus: 'select';
  locationdefaultreturncost: 'currency';
  locationdemandsource: 'select';
  locationfixedlotsize: 'float';
  locationinvtclassification: 'select';
  locationinvtcountinterval: 'integer';
  locationlastinvtcountdate: 'date';
  locationleadtime: 'integer';
  locationnextinvtcountdate: 'date';
  locationpreferredstocklevel: 'float';
  locationqtyavailforstorepickup: 'float';
  locationquantityavailable: 'float';
  locationquantitybackordered: 'float';
  locationquantitycommitted: 'float';
  locationquantityintransit: 'float';
  locationquantityonhand: 'float';
  locationquantityonorder: 'float';
  locationreorderpoint: 'float';
  locationsafetystocklevel: 'float';
  locationstorepickupbufferstock: 'float';
  locationsupplylotsizingmethod: 'select';
  locationsupplytype: 'select';
  locationtotalvalue: 'currency';
  manufacturer: 'text';
  manufactureraddr1: 'text';
  manufacturercity: 'text';
  manufacturerstate: 'text';
  manufacturertariff: 'text';
  manufacturertaxid: 'text';
  manufacturerzip: 'text';
  matchbilltoreceipt: 'checkbox';
  matrix: 'checkbox';
  matrixchild: 'checkbox';
  maximumquantity: 'integer';
  metataghtml: 'clobtext';
  minimumquantity: 'integer';
  mossapplies: 'checkbox';
  mpn: 'text';
  multmanufactureaddr: 'checkbox';
  nextagcategory: 'text';
  nextagproductfeed: 'checkbox';
  nextinvtcountdate: 'date';
  numactivelistings: 'integer';
  numberalloweddownloads: 'float';
  numcurrentlylisted: 'integer';
  obsoletedate: 'date';
  obsoleterevision: 'select';
  offersupport: 'checkbox';
  onlinecustomerprice: 'currency';
  onspecial: 'checkbox';
  othervendor: 'select';
  outofstockbehavior: 'select';
  overallquantitypricingtype: 'select';
  pagetitle: 'text';
  parent: 'select';
  preferencecriterion: 'text';
  preferredbin: 'checkbox';
  preferredlocation: 'select';
  preferredstocklevel: 'float';
  preferredstockleveldays: 'integer';
  price: 'currency';
  pricesincludetax: 'checkbox';
  pricinggroup: 'select';
  primarycategory: 'integer';
  purchaseorderamount: 'float';
  purchaseorderquantity: 'float';
  purchaseorderquantitydiff: 'float';
  purchaseunit: 'select';
  quantityavailable: 'float';
  quantitybackordered: 'float';
  quantitycommitted: 'float';
  quantityonhand: 'float';
  quantityonorder: 'float';
  quantitypricingschedule: 'select';
  receiptamount: 'float';
  receiptquantity: 'float';
  receiptquantitydiff: 'float';
  reordermultiple: 'integer';
  reorderpoint: 'float';
  reserveprice: 'currency';
  revrecforecastrule: 'select';
  revrecschedule: 'select';
  safetystocklevel: 'float';
  safetystockleveldays: 'integer';
  salesdescription: 'text';
  saleunit: 'select';
  sameasprimarybookamortization: 'checkbox';
  sameasprimarybookrevrec: 'checkbox';
  schedulebcode: 'select';
  schedulebnumber: 'text';
  schedulebquantity: 'text';
  searchkeywords: 'text';
  seasonaldemand: 'checkbox';
  sellonebay: 'checkbox';
  serialnumber: 'text';
  serialnumberlocation: 'select';
  shipindividually: 'checkbox';
  shippackage: 'select';
  shippingrate: 'currency';
  shoppingdotcomcategory: 'text';
  shoppingproductfeed: 'checkbox';
  shopzillacategoryid: 'integer';
  shopzillaproductfeed: 'checkbox';
  sitemappriority: 'float';
  softdescriptor: 'select';
  startingprice: 'currency';
  stockdescription: 'text';
  stockunit: 'select';
  storedescription: 'clobtext';
  subsidiary: 'select';
  subtype: 'select';
  supplylotsizingmethod: 'select';
  supplyreplenishmentmethod: 'select';
  supplytype: 'select';
  taxcode: 'select';
  taxschedule: 'select';
  thumbnailurl: 'text';
  totalvalue: 'currency';
  tracklandedcost: 'checkbox';
  transferprice: 'float';
  type: 'select';
  unitstype: 'select';
  upccode: 'text';
  urlcomponent: 'text';
  usebins: 'checkbox';
  usecomponentyield: 'checkbox';
  usemarginalrates: 'checkbox';
  vendor: 'select';
  vendorcode: 'text';
  vendorcost: 'currency';
  vendorcostentered: 'currency';
  vendorname: 'text';
  vendorpricecurrency: 'select';
  vsoedeferral: 'select';
  vsoedelivered: 'checkbox';
  vsoepermitdiscount: 'select';
  vsoeprice: 'float';
  vsoesopgroup: 'select';
  website: 'select';
  weight: 'float';
  yahooproductfeed: 'checkbox';
}


// Search Column Types

/** Item (item) Search Column Type definitions. */
export interface itemSearchColumnTypes {accbookrevrecforecastrule: 'select';
  accountingbook: 'select';
  accountingbookamortization: 'select';
  accountingbookcreateplanson: 'select';
  accountingbookrevrecrule: 'select';
  accountingbookrevrecschedule: 'select';
  alternatedemandsourceitem: 'text';
  assetaccount: 'select';
  atpleadtime: 'float';
  atpmethod: 'text';
  autoleadtime: 'checkbox';
  autopreferredstocklevel: 'checkbox';
  autoreorderpoint: 'checkbox';
  availabletopartners: 'checkbox';
  averagecost: 'currency2';
  backwardconsumptiondays: 'integer';
  baseprice: 'currency2';
  billexchratevarianceacct: 'select';
  billpricevarianceacct: 'select';
  billqtyvarianceacct: 'select';
  binnumber: 'text';
  binonhandavail: 'float';
  binonhandcount: 'float';
  bomquantity: 'float';
  buildentireassembly: 'checkbox';
  buildtime: 'float';
  buyitnowprice: 'currency';
  category: 'text';
  categorynohierarchy: 'text';
  categorypreferred: 'text';
  class: 'select';
  classnohierarchy: 'select';
  componentyield: 'float';
  contingentrevenuehandling: 'checkbox';
  copydescription: 'checkbox';
  correlateditem: 'select';
  correlateditemcorrelation: 'float';
  correlateditemcount: 'integer';
  correlateditemlift: 'float';
  correlateditempurchaserate: 'float';
  cost: 'currency2';
  costaccountingstatus: 'text';
  costcategory: 'text';
  costestimate: 'currency2';
  costestimatetype: 'text';
  costingmethod: 'select';
  countryofmanufacture: 'text';
  created: 'datetime';
  createjob: 'checkbox';
  createrevenueplanson: 'select';
  currentstandardcost: 'currency2';
  currentstdcosteffectivedate: 'date';
  custreturnvarianceaccount: 'select';
  dateviewed: 'datetime';
  daysbeforeexpiration: 'text';
  defaultreturncost: 'currency2';
  deferredexpenseaccount: 'select';
  deferredrevenueaccount: 'select';
  deferrevrec: 'checkbox';
  demandmodifier: 'percent';
  demandsource: 'text';
  department: 'select';
  departmentnohierarchy: 'select';
  directrevenueposting: 'checkbox';
  displayinebaystore: 'checkbox';
  displayname: 'text';
  distributioncategory: 'text';
  distributionnetwork: 'text';
  dontshowprice: 'checkbox';
  ebayitemdescription: 'clobtext';
  ebayitemsubtitle: 'text';
  ebayitemtitle: 'text';
  ebayrelistingoption: 'text';
  effectivebomcontrol: 'text';
  effectivedate: 'date';
  effectiverevision: 'select';
  endauctionswhenoutofstock: 'checkbox';
  excludefromsitemap: 'checkbox';
  expenseaccount: 'select';
  externalid: 'select';
  featureddescription: 'clobtext';
  feeddescription: 'text';
  feedname: 'text';
  fixedlotsize: 'float';
  formulacurrency: 'currency';
  formuladate: 'date';
  formuladatetime: 'datetime';
  formulanumeric: 'float';
  formulapercent: 'percent';
  formulatext: 'text';
  forwardconsumptiondays: 'integer';
  fraudrisk: 'select';
  froogleproductfeed: 'checkbox';
  fxcost: 'currency2';
  gainlossaccount: 'select';
  generateaccruals: 'checkbox';
  giftcertauthcode: 'text';
  giftcertemail: 'text';
  giftcertexpirationdate: 'text';
  giftcertfrom: 'text';
  giftcertmessage: 'text';
  giftcertoriginalamount: 'text';
  giftcertrecipient: 'text';
  hits: 'integer';
  imageurl: 'text';
  incomeaccount: 'select';
  intercodefrevaccount: 'select';
  intercoexpenseaccount: 'select';
  intercoincomeaccount: 'select';
  internalid: 'select';
  inventorylocation: 'select';
  invtclassification: 'text';
  invtcountinterval: 'integer';
  isavailable: 'checkbox';
  isdropshipitem: 'checkbox';
  isfulfillable: 'checkbox';
  isgcocompliant: 'checkbox';
  isinactive: 'checkbox';
  islotitem: 'checkbox';
  isonline: 'checkbox';
  isserialitem: 'checkbox';
  isspecialorderitem: 'checkbox';
  isspecialworkorderitem: 'checkbox';
  isstorepickupallowed: 'checkbox';
  issueproduct: 'select';
  istaxable: 'checkbox';
  isvsoebundle: 'checkbox';
  iswip: 'checkbox';
  itemid: 'text';
  itemurl: 'text';
  lastinvtcountdate: 'date';
  lastpurchaseprice: 'currency';
  lastquantityavailablechange: 'datetime';
  lastviewed: 'datetime';
  leadtime: 'integer';
  liabilityaccount: 'select';
  listingduration: 'text';
  location: 'select';
  locationallowstorepickup: 'checkbox';
  locationatpleadtime: 'float';
  locationaveragecost: 'currency2';
  locationbinquantityavailable: 'float';
  locationbuildtime: 'float';
  locationcost: 'currency';
  locationcostaccountingstatus: 'text';
  locationdefaultreturncost: 'currency2';
  locationdemandsource: 'text';
  locationfixedlotsize: 'float';
  locationinvtclassification: 'text';
  locationinvtcountinterval: 'integer';
  locationlastinvtcountdate: 'date';
  locationleadtime: 'integer';
  locationnextinvtcountdate: 'date';
  locationnohierarchy: 'select';
  locationpreferredstocklevel: 'float';
  locationqtyavailforstorepickup: 'float';
  locationquantityavailable: 'float';
  locationquantitybackordered: 'float';
  locationquantitycommitted: 'float';
  locationquantityintransit: 'float';
  locationquantityonhand: 'float';
  locationquantityonorder: 'float';
  locationreorderpoint: 'float';
  locationsafetystocklevel: 'float';
  locationstorepickupbufferstock: 'float';
  locationsupplylotsizingmethod: 'text';
  locationsupplytype: 'text';
  locationtotalvalue: 'currency2';
  manufacturer: 'text';
  manufactureraddr1: 'text';
  manufacturercity: 'text';
  manufacturerstate: 'text';
  manufacturertariff: 'text';
  manufacturertaxid: 'text';
  manufacturerzip: 'text';
  matchbilltoreceipt: 'checkbox';
  maximumquantity: 'text';
  memberitem: 'select';
  memberquantity: 'float';
  metataghtml: 'clobtext';
  minimumquantity: 'text';
  modified: 'datetime';
  mossapplies: 'checkbox';
  mpn: 'text';
  multmanufactureaddr: 'checkbox';
  nextagcategory: 'text';
  nextagproductfeed: 'checkbox';
  nextinvtcountdate: 'date';
  nopricemessage: 'text';
  numactivelistings: 'integer';
  numberalloweddownloads: 'text';
  numcurrentlylisted: 'integer';
  obsoletedate: 'date';
  obsoleterevision: 'select';
  offersupport: 'checkbox';
  onlinecustomerprice: 'currency';
  onlineprice: 'currency';
  onspecial: 'checkbox';
  otherprices: 'currency';
  othervendor: 'select';
  outofstockbehavior: 'text';
  outofstockmessage: 'text';
  overallquantitypricingtype: 'select';
  pagetitle: 'textarea';
  parent: 'select';
  preferencecriterion: 'text';
  preferredbin: 'checkbox';
  preferredlocation: 'select';
  preferredstocklevel: 'float';
  preferredstockleveldays: 'integer';
  pricesincludetax: 'checkbox';
  pricinggroup: 'select';
  primarycategory: 'text';
  prodpricevarianceacct: 'select';
  prodqtyvarianceacct: 'select';
  purchasedescription: 'text';
  purchaseorderamount: 'float';
  purchaseorderquantity: 'float';
  purchaseorderquantitydiff: 'float';
  purchasepricevarianceacct: 'select';
  purchaseunit: 'select';
  quantityavailable: 'float';
  quantitybackordered: 'float';
  quantitycommitted: 'float';
  quantityonhand: 'float';
  quantityonorder: 'float';
  quantitypricingschedule: 'select';
  receiptamount: 'float';
  receiptquantity: 'float';
  receiptquantitydiff: 'float';
  reordermultiple: 'integer';
  reorderpoint: 'float';
  reserveprice: 'currency';
  revrecforecastrule: 'select';
  revreclassfxaccount: 'select';
  revrecschedule: 'select';
  roundupascomponent: 'checkbox';
  safetystocklevel: 'float';
  safetystockleveldays: 'integer';
  salesdescription: 'text';
  salestaxcode: 'select';
  saleunit: 'select';
  sameasprimarybookamortization: 'checkbox';
  sameasprimarybookrevrec: 'checkbox';
  schedulebcode: 'text';
  schedulebnumber: 'text';
  schedulebquantity: 'text';
  scrapacct: 'select';
  searchkeywords: 'text';
  seasonaldemand: 'checkbox';
  sellonebay: 'checkbox';
  serialnumber: 'text';
  serialnumberlocation: 'text';
  shipindividually: 'checkbox';
  shippackage: 'select';
  shippingrate: 'currency';
  shoppingdotcomcategory: 'text';
  shoppingproductfeed: 'checkbox';
  shopzillacategoryid: 'integer';
  shopzillaproductfeed: 'checkbox';
  sitemappriority: 'float';
  softdescriptor: 'select';
  startingprice: 'currency';
  stockdescription: 'text';
  stockunit: 'select';
  storedescription: 'text';
  storedetaileddescription: 'clobtext';
  storedisplayimage: 'select';
  storedisplayname: 'text';
  storedisplaythumbnail: 'select';
  subsidiary: 'select';
  subsidiarynohierarchy: 'select';
  subtype: 'text';
  supplylotsizingmethod: 'text';
  supplyreplenishmentmethod: 'text';
  supplytype: 'text';
  taxschedule: 'select';
  thumbnailurl: 'text';
  totalvalue: 'currency2';
  tracklandedcost: 'checkbox';
  transferprice: 'currency2';
  type: 'select';
  unbuildvarianceaccount: 'select';
  unitstype: 'select';
  upccode: 'text';
  urlcomponent: 'text';
  usebins: 'checkbox';
  usecomponentyield: 'checkbox';
  usemarginalrates: 'checkbox';
  vendor: 'select';
  vendorcode: 'text';
  vendorcost: 'currency';
  vendorcostentered: 'currency';
  vendorname: 'text';
  vendorpricecurrency: 'text';
  vendorschedule: 'select';
  vendreturnvarianceaccount: 'select';
  vsoedeferral: 'select';
  vsoedelivered: 'checkbox';
  vsoepermitdiscount: 'select';
  vsoeprice: 'currency2';
  vsoesopgroup: 'checkbox';
  website: 'select';
  weight: 'float';
  weightunit: 'select';
  wipacct: 'select';
  wipvarianceacct: 'select';
  yahooproductfeed: 'checkbox';
}