// This file is automatically generated - don't edit it. 
// Search Types for record Non-Inventory Part (noninventoryitem)

// Search Columns

/** Non-Inventory Part (noninventoryitem) Search Columns definition */
export interface noninventoryitemSearchColumn {
}


// Search Filters

/** Non-Inventory Part (noninventoryitem) Search Filters definition */
export interface noninventoryitemSearchFilter {
}


// Search Joins
/** Non-Inventory Part (noninventoryitem) Search Joins definition type. */
export interface noninventoryitemSearchJoin {
}