// This file is automatically generated - don't edit it. 
// Search Types for record Website (website)

// Search Columns

/** Website (website) Search Columns definition */
export interface websiteSearchColumn {
}


// Search Filters

/** Website (website) Search Filters definition */
export interface websiteSearchFilter {
}


// Search Joins
/** Website (website) Search Joins definition type. */
export interface websiteSearchJoin {
}